//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:02:17 PM EEST 
//


package oasis.names.tc.emergency.edxl.tep._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.emergency.edxl.tep._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.emergency.edxl.tep._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TEPMessage }
     * 
     */
    public TEPMessage createTEPMessage() {
        return new TEPMessage();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link IncidentIDType }
     * 
     */
    public IncidentIDType createIncidentIDType() {
        return new IncidentIDType();
    }

    /**
     * Create an instance of {@link HealthCareProviderType }
     * 
     */
    public HealthCareProviderType createHealthCareProviderType() {
        return new HealthCareProviderType();
    }

    /**
     * Create an instance of {@link PatientEncounterType }
     * 
     */
    public PatientEncounterType createPatientEncounterType() {
        return new PatientEncounterType();
    }

    /**
     * Create an instance of {@link MedicationType }
     * 
     */
    public MedicationType createMedicationType() {
        return new MedicationType();
    }

    /**
     * Create an instance of {@link PatientAgeType }
     * 
     */
    public PatientAgeType createPatientAgeType() {
        return new PatientAgeType();
    }

    /**
     * Create an instance of {@link PatientIDType }
     * 
     */
    public PatientIDType createPatientIDType() {
        return new PatientIDType();
    }

    /**
     * Create an instance of {@link SituationType }
     * 
     */
    public SituationType createSituationType() {
        return new SituationType();
    }

    /**
     * Create an instance of {@link TransportType }
     * 
     */
    public TransportType createTransportType() {
        return new TransportType();
    }

    /**
     * Create an instance of {@link PatientCareType }
     * 
     */
    public PatientCareType createPatientCareType() {
        return new PatientCareType();
    }

    /**
     * Create an instance of {@link PatientTransferType }
     * 
     */
    public PatientTransferType createPatientTransferType() {
        return new PatientTransferType();
    }

}
