//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:03:54 PM EEST 
//


package oasis.names.tc.emergency.EDXL.TEP._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Group of elements used to extend/augment an EDXL data standard
 * 
 * <p>Java class for ParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameURI" type="{urn:oasis:names:tc:emergency:edxl:extension:1.0}ParameterNameType"/>
 *         &lt;element name="value" type="{urn:oasis:names:tc:emergency:edxl:extension:1.0}ParameterValueType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterType", namespace = "urn:oasis:names:tc:emergency:edxl:extension:1.0", propOrder = {
    "nameURI",
    "value"
})
public class ParameterType {

    @XmlElement(required = true)
    protected ParameterNameType nameURI;
    @XmlElement(required = true)
    protected List<ParameterValueType> value;

    /**
     * Gets the value of the nameURI property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterNameType }
     *     
     */
    public ParameterNameType getNameURI() {
        return nameURI;
    }

    /**
     * Sets the value of the nameURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterNameType }
     *     
     */
    public void setNameURI(ParameterNameType value) {
        this.nameURI = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterValueType }
     * 
     * 
     */
    public List<ParameterValueType> getValue() {
        if (value == null) {
            value = new ArrayList<ParameterValueType>();
        }
        return this.value;
    }

}
