//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:03:54 PM EEST 
//


package oasis.names.tc.emergency.EDXL.TEP._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 Reusable complex type for a party. A party is a person or an organisation
 *             
 * 
 * <p>Java class for PartyNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyNameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}NameLine" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PersonName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}PersonNameType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OrganisationName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}OrganisationNameType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="PartyNameID" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}String" />
 *       &lt;attribute name="PartyNameIDType" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}PartyNameIDTypeList" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyNameType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl", propOrder = {
    "nameLine",
    "personName",
    "organisationName"
})
public class PartyNameType {

    @XmlElement(name = "NameLine")
    protected List<NameLine> nameLine;
    @XmlElement(name = "PersonName")
    protected List<PartyNameType.PersonName> personName;
    @XmlElement(name = "OrganisationName")
    protected List<PartyNameType.OrganisationName> organisationName;
    @XmlAttribute(name = "PartyNameID", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partyNameID;
    @XmlAttribute(name = "PartyNameIDType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partyNameIDType;

    /**
     * Gets the value of the nameLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameLine }
     * 
     * 
     */
    public List<NameLine> getNameLine() {
        if (nameLine == null) {
            nameLine = new ArrayList<NameLine>();
        }
        return this.nameLine;
    }

    /**
     * Gets the value of the personName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyNameType.PersonName }
     * 
     * 
     */
    public List<PartyNameType.PersonName> getPersonName() {
        if (personName == null) {
            personName = new ArrayList<PartyNameType.PersonName>();
        }
        return this.personName;
    }

    /**
     * Gets the value of the organisationName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organisationName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganisationName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyNameType.OrganisationName }
     * 
     * 
     */
    public List<PartyNameType.OrganisationName> getOrganisationName() {
        if (organisationName == null) {
            organisationName = new ArrayList<PartyNameType.OrganisationName>();
        }
        return this.organisationName;
    }

    /**
     * Gets the value of the partyNameID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyNameID() {
        return partyNameID;
    }

    /**
     * Sets the value of the partyNameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyNameID(String value) {
        this.partyNameID = value;
    }

    /**
     * Gets the value of the partyNameIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyNameIDType() {
        return partyNameIDType;
    }

    /**
     * Sets the value of the partyNameIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyNameIDType(String value) {
        this.partyNameIDType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}OrganisationNameType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrganisationName
        extends OrganisationNameType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}PersonNameType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PersonName
        extends PersonNameType
    {


    }

}
