//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:02:17 PM EEST 
//


package oasis.names.tc.emergency.edxl.tep._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import oasis.names.tc.emergency.edxl.ct._1.EDXLLocationType;
import oasis.names.tc.emergency.edxl.ct._1.ValueKeyType;


/**
 * Group of elements used to describe an instance of an encounter between a patient (patient) and an EMS Care Provider.
 * 
 * <p>Java class for PatientEncounterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientEncounterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="encounterID" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType"/>
 *         &lt;element name="encounterDateTime" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType"/>
 *         &lt;element name="locationCategory" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueKeyType"/>
 *         &lt;element name="encounterLocation" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLLocationType"/>
 *         &lt;element name="patientCare" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}PatientCareType" maxOccurs="unbounded"/>
 *         &lt;element name="patientTransfer" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}PatientTransferType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientEncounterType", propOrder = {
    "encounterID",
    "encounterDateTime",
    "locationCategory",
    "encounterLocation",
    "patientCare",
    "patientTransfer"
})
public class PatientEncounterType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String encounterID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar encounterDateTime;
    @XmlElement(required = true)
    protected ValueKeyType locationCategory;
    @XmlElement(required = true)
    protected EDXLLocationType encounterLocation;
    @XmlElement(required = true)
    protected List<PatientCareType> patientCare;
    protected List<PatientTransferType> patientTransfer;

    /**
     * Gets the value of the encounterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncounterID() {
        return encounterID;
    }

    /**
     * Sets the value of the encounterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncounterID(String value) {
        this.encounterID = value;
    }

    /**
     * Gets the value of the encounterDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEncounterDateTime() {
        return encounterDateTime;
    }

    /**
     * Sets the value of the encounterDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEncounterDateTime(XMLGregorianCalendar value) {
        this.encounterDateTime = value;
    }

    /**
     * Gets the value of the locationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ValueKeyType }
     *     
     */
    public ValueKeyType getLocationCategory() {
        return locationCategory;
    }

    /**
     * Sets the value of the locationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueKeyType }
     *     
     */
    public void setLocationCategory(ValueKeyType value) {
        this.locationCategory = value;
    }

    /**
     * Gets the value of the encounterLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EDXLLocationType }
     *     
     */
    public EDXLLocationType getEncounterLocation() {
        return encounterLocation;
    }

    /**
     * Sets the value of the encounterLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXLLocationType }
     *     
     */
    public void setEncounterLocation(EDXLLocationType value) {
        this.encounterLocation = value;
    }

    /**
     * Gets the value of the patientCare property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientCare property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientCare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientCareType }
     * 
     * 
     */
    public List<PatientCareType> getPatientCare() {
        if (patientCare == null) {
            patientCare = new ArrayList<PatientCareType>();
        }
        return this.patientCare;
    }

    /**
     * Gets the value of the patientTransfer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientTransfer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientTransfer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientTransferType }
     * 
     * 
     */
    public List<PatientTransferType> getPatientTransfer() {
        if (patientTransfer == null) {
            patientTransfer = new ArrayList<PatientTransferType>();
        }
        return this.patientTransfer;
    }

}
