//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:03:54 PM EEST 
//


package oasis.names.tc.emergency.EDXL.TEP._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Group of elements used to describe Care Provider observations, evaluations, electronic measures and actual treatments and procedures taken for or performed on the patient at a particular point in time.
 * 
 * <p>Java class for PatientCareType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientCareType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patientCareRecordID" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType"/>
 *         &lt;element name="patientCareRecordDateTime" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType"/>
 *         &lt;element name="triageStatus" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}TriageStatusDefaultValues"/>
 *         &lt;element name="patientCurrentDisposition" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}PatientCurrentDispositionDefaultValues"/>
 *         &lt;element name="chiefComplaint" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType" minOccurs="0"/>
 *         &lt;element name="systolicBloodPressure" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="300"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="diastolicBloodPressure" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="300"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pulseRate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="320"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="respiratoryRate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cardiacMonitorRhythm" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType" minOccurs="0"/>
 *         &lt;element name="twelveLeadECGInterpretation" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType" minOccurs="0"/>
 *         &lt;element name="pulseOximetry" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}PercentageType" minOccurs="0"/>
 *         &lt;element name="CO2Level" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="bloodGlucoseLevel" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="temperature" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}DegreesCType" minOccurs="0"/>
 *         &lt;element name="totalGCS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="3"/>
 *               &lt;maxInclusive value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="medicationAdministered" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}MedicationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="proceduresPerformed" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType" minOccurs="0"/>
 *         &lt;element name="careProviderPrimaryImpression" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType" minOccurs="0"/>
 *         &lt;element name="seriousConcerns" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType" minOccurs="0"/>
 *         &lt;element name="contaminationRadiationContagionStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="acsCDCFieldTraumaCriteria" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="contingencyMedicalSpecialtyCode" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}ContingencyMedicalSpecialtyCodeDefaultValues" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientCareType", namespace = "urn:oasis:names:tc:emergency:EDXL:TEP:1.0", propOrder = {
    "patientCareRecordID",
    "patientCareRecordDateTime",
    "triageStatus",
    "patientCurrentDisposition",
    "chiefComplaint",
    "systolicBloodPressure",
    "diastolicBloodPressure",
    "pulseRate",
    "respiratoryRate",
    "cardiacMonitorRhythm",
    "twelveLeadECGInterpretation",
    "pulseOximetry",
    "co2Level",
    "bloodGlucoseLevel",
    "temperature",
    "totalGCS",
    "medicationAdministered",
    "proceduresPerformed",
    "careProviderPrimaryImpression",
    "seriousConcerns",
    "contaminationRadiationContagionStatus",
    "acsCDCFieldTraumaCriteria",
    "contingencyMedicalSpecialtyCode"
})
public class PatientCareType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String patientCareRecordID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar patientCareRecordDateTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected TriageStatusDefaultValues triageStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected PatientCurrentDispositionDefaultValues patientCurrentDisposition;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String chiefComplaint;
    protected Integer systolicBloodPressure;
    protected Integer diastolicBloodPressure;
    protected Integer pulseRate;
    protected Integer respiratoryRate;
    protected ValueListType cardiacMonitorRhythm;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String twelveLeadECGInterpretation;
    protected Float pulseOximetry;
    @XmlElement(name = "CO2Level")
    @XmlSchemaType(name = "unsignedInt")
    protected Long co2Level;
    protected Integer bloodGlucoseLevel;
    protected Float temperature;
    protected Integer totalGCS;
    protected List<MedicationType> medicationAdministered;
    protected ValueListType proceduresPerformed;
    protected ValueListType careProviderPrimaryImpression;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String seriousConcerns;
    protected Boolean contaminationRadiationContagionStatus;
    protected Boolean acsCDCFieldTraumaCriteria;
    @XmlSchemaType(name = "token")
    protected ContingencyMedicalSpecialtyCodeDefaultValues contingencyMedicalSpecialtyCode;

    /**
     * Gets the value of the patientCareRecordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientCareRecordID() {
        return patientCareRecordID;
    }

    /**
     * Sets the value of the patientCareRecordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientCareRecordID(String value) {
        this.patientCareRecordID = value;
    }

    /**
     * Gets the value of the patientCareRecordDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPatientCareRecordDateTime() {
        return patientCareRecordDateTime;
    }

    /**
     * Sets the value of the patientCareRecordDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPatientCareRecordDateTime(XMLGregorianCalendar value) {
        this.patientCareRecordDateTime = value;
    }

    /**
     * Gets the value of the triageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TriageStatusDefaultValues }
     *     
     */
    public TriageStatusDefaultValues getTriageStatus() {
        return triageStatus;
    }

    /**
     * Sets the value of the triageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriageStatusDefaultValues }
     *     
     */
    public void setTriageStatus(TriageStatusDefaultValues value) {
        this.triageStatus = value;
    }

    /**
     * Gets the value of the patientCurrentDisposition property.
     * 
     * @return
     *     possible object is
     *     {@link PatientCurrentDispositionDefaultValues }
     *     
     */
    public PatientCurrentDispositionDefaultValues getPatientCurrentDisposition() {
        return patientCurrentDisposition;
    }

    /**
     * Sets the value of the patientCurrentDisposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientCurrentDispositionDefaultValues }
     *     
     */
    public void setPatientCurrentDisposition(PatientCurrentDispositionDefaultValues value) {
        this.patientCurrentDisposition = value;
    }

    /**
     * Gets the value of the chiefComplaint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChiefComplaint() {
        return chiefComplaint;
    }

    /**
     * Sets the value of the chiefComplaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChiefComplaint(String value) {
        this.chiefComplaint = value;
    }

    /**
     * Gets the value of the systolicBloodPressure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSystolicBloodPressure() {
        return systolicBloodPressure;
    }

    /**
     * Sets the value of the systolicBloodPressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSystolicBloodPressure(Integer value) {
        this.systolicBloodPressure = value;
    }

    /**
     * Gets the value of the diastolicBloodPressure property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDiastolicBloodPressure() {
        return diastolicBloodPressure;
    }

    /**
     * Sets the value of the diastolicBloodPressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDiastolicBloodPressure(Integer value) {
        this.diastolicBloodPressure = value;
    }

    /**
     * Gets the value of the pulseRate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPulseRate() {
        return pulseRate;
    }

    /**
     * Sets the value of the pulseRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPulseRate(Integer value) {
        this.pulseRate = value;
    }

    /**
     * Gets the value of the respiratoryRate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRespiratoryRate() {
        return respiratoryRate;
    }

    /**
     * Sets the value of the respiratoryRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRespiratoryRate(Integer value) {
        this.respiratoryRate = value;
    }

    /**
     * Gets the value of the cardiacMonitorRhythm property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getCardiacMonitorRhythm() {
        return cardiacMonitorRhythm;
    }

    /**
     * Sets the value of the cardiacMonitorRhythm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setCardiacMonitorRhythm(ValueListType value) {
        this.cardiacMonitorRhythm = value;
    }

    /**
     * Gets the value of the twelveLeadECGInterpretation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwelveLeadECGInterpretation() {
        return twelveLeadECGInterpretation;
    }

    /**
     * Sets the value of the twelveLeadECGInterpretation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwelveLeadECGInterpretation(String value) {
        this.twelveLeadECGInterpretation = value;
    }

    /**
     * Gets the value of the pulseOximetry property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPulseOximetry() {
        return pulseOximetry;
    }

    /**
     * Sets the value of the pulseOximetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPulseOximetry(Float value) {
        this.pulseOximetry = value;
    }

    /**
     * Gets the value of the co2Level property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCO2Level() {
        return co2Level;
    }

    /**
     * Sets the value of the co2Level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCO2Level(Long value) {
        this.co2Level = value;
    }

    /**
     * Gets the value of the bloodGlucoseLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBloodGlucoseLevel() {
        return bloodGlucoseLevel;
    }

    /**
     * Sets the value of the bloodGlucoseLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBloodGlucoseLevel(Integer value) {
        this.bloodGlucoseLevel = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTemperature(Float value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the totalGCS property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalGCS() {
        return totalGCS;
    }

    /**
     * Sets the value of the totalGCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalGCS(Integer value) {
        this.totalGCS = value;
    }

    /**
     * Gets the value of the medicationAdministered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationAdministered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationAdministered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationType }
     * 
     * 
     */
    public List<MedicationType> getMedicationAdministered() {
        if (medicationAdministered == null) {
            medicationAdministered = new ArrayList<MedicationType>();
        }
        return this.medicationAdministered;
    }

    /**
     * Gets the value of the proceduresPerformed property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getProceduresPerformed() {
        return proceduresPerformed;
    }

    /**
     * Sets the value of the proceduresPerformed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setProceduresPerformed(ValueListType value) {
        this.proceduresPerformed = value;
    }

    /**
     * Gets the value of the careProviderPrimaryImpression property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getCareProviderPrimaryImpression() {
        return careProviderPrimaryImpression;
    }

    /**
     * Sets the value of the careProviderPrimaryImpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setCareProviderPrimaryImpression(ValueListType value) {
        this.careProviderPrimaryImpression = value;
    }

    /**
     * Gets the value of the seriousConcerns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriousConcerns() {
        return seriousConcerns;
    }

    /**
     * Sets the value of the seriousConcerns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriousConcerns(String value) {
        this.seriousConcerns = value;
    }

    /**
     * Gets the value of the contaminationRadiationContagionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContaminationRadiationContagionStatus() {
        return contaminationRadiationContagionStatus;
    }

    /**
     * Sets the value of the contaminationRadiationContagionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContaminationRadiationContagionStatus(Boolean value) {
        this.contaminationRadiationContagionStatus = value;
    }

    /**
     * Gets the value of the acsCDCFieldTraumaCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcsCDCFieldTraumaCriteria() {
        return acsCDCFieldTraumaCriteria;
    }

    /**
     * Sets the value of the acsCDCFieldTraumaCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcsCDCFieldTraumaCriteria(Boolean value) {
        this.acsCDCFieldTraumaCriteria = value;
    }

    /**
     * Gets the value of the contingencyMedicalSpecialtyCode property.
     * 
     * @return
     *     possible object is
     *     {@link ContingencyMedicalSpecialtyCodeDefaultValues }
     *     
     */
    public ContingencyMedicalSpecialtyCodeDefaultValues getContingencyMedicalSpecialtyCode() {
        return contingencyMedicalSpecialtyCode;
    }

    /**
     * Sets the value of the contingencyMedicalSpecialtyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContingencyMedicalSpecialtyCodeDefaultValues }
     *     
     */
    public void setContingencyMedicalSpecialtyCode(ContingencyMedicalSpecialtyCodeDefaultValues value) {
        this.contingencyMedicalSpecialtyCode = value;
    }

}
