//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:03:54 PM EEST 
//


package oasis.names.tc.emergency.EDXL.TEP._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientAgeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientAgeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="estimated" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EstimateType"/>
 *         &lt;element name="units" type="{urn:oasis:names:tc:emergency:EDXL:TEP:1.0}AgeUnitsDefaultValues"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientAgeType", namespace = "urn:oasis:names:tc:emergency:EDXL:TEP:1.0", propOrder = {
    "age",
    "estimated",
    "units"
})
public class PatientAgeType {

    @XmlSchemaType(name = "unsignedInt")
    protected long age;
    protected boolean estimated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected AgeUnitsDefaultValues units;

    /**
     * Gets the value of the age property.
     * 
     */
    public long getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(long value) {
        this.age = value;
    }

    /**
     * Gets the value of the estimated property.
     * 
     */
    public boolean isEstimated() {
        return estimated;
    }

    /**
     * Sets the value of the estimated property.
     * 
     */
    public void setEstimated(boolean value) {
        this.estimated = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link AgeUnitsDefaultValues }
     *     
     */
    public AgeUnitsDefaultValues getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeUnitsDefaultValues }
     *     
     */
    public void setUnits(AgeUnitsDefaultValues value) {
        this.units = value;
    }

}
