//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:03:54 PM EEST 
//


package oasis.names.tc.emergency.EDXL.TEP._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A container for defining the unique characteristics of a person only
 *             
 * 
 * <p>Java class for PersonDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl}PersonName" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}Addresses" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ContactNumbers" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ElectronicAddressIdentifiers" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}Identifiers" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonDetailsType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil", propOrder = {
    "personName",
    "addresses",
    "contactNumbers",
    "electronicAddressIdentifiers",
    "identifiers"
})
@XmlSeeAlso({
    PersonDetailsType.class,
    PersonDetails.class
})
public class PersonDetailsType2 {

    @XmlElement(name = "PersonName", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xnl", required = true)
    protected List<PersonNameType> personName;
    @XmlElement(name = "Addresses")
    protected Addresses addresses;
    @XmlElement(name = "ContactNumbers")
    protected ContactNumbers contactNumbers;
    @XmlElement(name = "ElectronicAddressIdentifiers")
    protected ElectronicAddressIdentifiers electronicAddressIdentifiers;
    @XmlElement(name = "Identifiers")
    protected Identifiers identifiers;

    /**
     * Gets the value of the personName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonNameType }
     * 
     * 
     */
    public List<PersonNameType> getPersonName() {
        if (personName == null) {
            personName = new ArrayList<PersonNameType>();
        }
        return this.personName;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link Addresses }
     *     
     */
    public Addresses getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addresses }
     *     
     */
    public void setAddresses(Addresses value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the contactNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ContactNumbers }
     *     
     */
    public ContactNumbers getContactNumbers() {
        return contactNumbers;
    }

    /**
     * Sets the value of the contactNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactNumbers }
     *     
     */
    public void setContactNumbers(ContactNumbers value) {
        this.contactNumbers = value;
    }

    /**
     * Gets the value of the electronicAddressIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicAddressIdentifiers }
     *     
     */
    public ElectronicAddressIdentifiers getElectronicAddressIdentifiers() {
        return electronicAddressIdentifiers;
    }

    /**
     * Sets the value of the electronicAddressIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicAddressIdentifiers }
     *     
     */
    public void setElectronicAddressIdentifiers(ElectronicAddressIdentifiers value) {
        this.electronicAddressIdentifiers = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Identifiers }
     *     
     */
    public Identifiers getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifiers }
     *     
     */
    public void setIdentifiers(Identifiers value) {
        this.identifiers = value;
    }

}
