//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 03:33:45 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:emergency:EDXL:DE:1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package oasis.names.tc.emergency.EDXL.DE._1;
