//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 03:33:45 PM EET 
//


package oasis.names.tc.emergency.EDXL.DE._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Report"/>
 *     &lt;enumeration value="Update"/>
 *     &lt;enumeration value="Cancel"/>
 *     &lt;enumeration value="Request"/>
 *     &lt;enumeration value="Response"/>
 *     &lt;enumeration value="Dispatch"/>
 *     &lt;enumeration value="Ack"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="SensorConfiguration"/>
 *     &lt;enumeration value="SensorControl"/>
 *     &lt;enumeration value="SensorStatus"/>
 *     &lt;enumeration value="SensorDetection"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeValues")
@XmlEnum
public enum TypeValues {

    @XmlEnumValue("Report")
    REPORT("Report"),
    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Cancel")
    CANCEL("Cancel"),
    @XmlEnumValue("Request")
    REQUEST("Request"),
    @XmlEnumValue("Response")
    RESPONSE("Response"),
    @XmlEnumValue("Dispatch")
    DISPATCH("Dispatch"),
    @XmlEnumValue("Ack")
    ACK("Ack"),
    @XmlEnumValue("Error")
    ERROR("Error"),
    @XmlEnumValue("SensorConfiguration")
    SENSOR_CONFIGURATION("SensorConfiguration"),
    @XmlEnumValue("SensorControl")
    SENSOR_CONTROL("SensorControl"),
    @XmlEnumValue("SensorStatus")
    SENSOR_STATUS("SensorStatus"),
    @XmlEnumValue("SensorDetection")
    SENSOR_DETECTION("SensorDetection");
    private final String value;

    TypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeValues fromValue(String v) {
        for (TypeValues c: TypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
