//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 03:33:45 PM EET 
//


package oasis.names.tc.emergency.EDXL.DE._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for valueSchemeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="valueSchemeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="explicitAddressScheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="explicitAddressValue" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "valueSchemeType", propOrder = {
    "explicitAddressScheme",
    "explicitAddressValue"
})
public class ValueSchemeType {

    @XmlElement(required = true)
    protected String explicitAddressScheme;
    @XmlElement(required = true)
    protected List<String> explicitAddressValue;

    /**
     * Gets the value of the explicitAddressScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplicitAddressScheme() {
        return explicitAddressScheme;
    }

    /**
     * Sets the value of the explicitAddressScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplicitAddressScheme(String value) {
        this.explicitAddressScheme = value;
    }

    /**
     * Gets the value of the explicitAddressValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the explicitAddressValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExplicitAddressValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExplicitAddressValue() {
        if (explicitAddressValue == null) {
            explicitAddressValue = new ArrayList<String>();
        }
        return this.explicitAddressValue;
    }

    public void setExplicitAddressValue(List<String> explicitAddressValue) {
        this.explicitAddressValue = explicitAddressValue;
    }
    
    

}
