//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:02:17 PM EEST 
//


package oasis.names.tc.emergency.edxl.ciq._1_0.xpil;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactNumber" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContactNumberElement" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct>String">
 *                           &lt;attribute name="Type" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ContactNumberElementList" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="CommunicationMediaType" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}CommunicationMediaTypeList" />
 *                 &lt;attribute name="Usage" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ContactNumberUsageList" />
 *                 &lt;attribute name="ContactHours" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}String" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactNumber"
})
@XmlRootElement(name = "ContactNumbers")
public class ContactNumbers {

    @XmlElement(name = "ContactNumber", required = true)
    protected List<ContactNumbers.ContactNumber> contactNumber;

    /**
     * Gets the value of the contactNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactNumbers.ContactNumber }
     * 
     * 
     */
    public List<ContactNumbers.ContactNumber> getContactNumber() {
        if (contactNumber == null) {
            contactNumber = new ArrayList<ContactNumbers.ContactNumber>();
        }
        return this.contactNumber;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContactNumberElement" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct>String">
     *                 &lt;attribute name="Type" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ContactNumberElementList" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="CommunicationMediaType" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}CommunicationMediaTypeList" />
     *       &lt;attribute name="Usage" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ContactNumberUsageList" />
     *       &lt;attribute name="ContactHours" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}String" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contactNumberElement"
    })
    public static class ContactNumber {

        @XmlElement(name = "ContactNumberElement")
        protected List<ContactNumbers.ContactNumber.ContactNumberElement> contactNumberElement;
        @XmlAttribute(name = "CommunicationMediaType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
        protected CommunicationMediaTypeList communicationMediaType;
        @XmlAttribute(name = "Usage", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String usage;
        @XmlAttribute(name = "ContactHours", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String contactHours;

        /**
         * Gets the value of the contactNumberElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contactNumberElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContactNumberElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ContactNumbers.ContactNumber.ContactNumberElement }
         * 
         * 
         */
        public List<ContactNumbers.ContactNumber.ContactNumberElement> getContactNumberElement() {
            if (contactNumberElement == null) {
                contactNumberElement = new ArrayList<ContactNumbers.ContactNumber.ContactNumberElement>();
            }
            return this.contactNumberElement;
        }

        /**
         * Gets the value of the communicationMediaType property.
         * 
         * @return
         *     possible object is
         *     {@link CommunicationMediaTypeList }
         *     
         */
        public CommunicationMediaTypeList getCommunicationMediaType() {
            return communicationMediaType;
        }

        /**
         * Sets the value of the communicationMediaType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommunicationMediaTypeList }
         *     
         */
        public void setCommunicationMediaType(CommunicationMediaTypeList value) {
            this.communicationMediaType = value;
        }

        /**
         * Gets the value of the usage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsage() {
            return usage;
        }

        /**
         * Sets the value of the usage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsage(String value) {
            this.usage = value;
        }

        /**
         * Gets the value of the contactHours property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactHours() {
            return contactHours;
        }

        /**
         * Sets the value of the contactHours property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactHours(String value) {
            this.contactHours = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct>String">
         *       &lt;attribute name="Type" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}ContactNumberElementList" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class ContactNumberElement {

            @XmlValue
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String value;
            @XmlAttribute(name = "Type", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
            protected ContactNumberElementList type;

            /**
             * 
             *                 Normalized and Collapsed String
             *             
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link ContactNumberElementList }
             *     
             */
            public ContactNumberElementList getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link ContactNumberElementList }
             *     
             */
            public void setType(ContactNumberElementList value) {
                this.type = value;
            }

        }

    }

}
