//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:02:17 PM EEST 
//


package oasis.names.tc.emergency.edxl.ciq._1_0.xpil;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import oasis.names.tc.emergency.edxl.ciq._1_0.ct.DataQualityTypeList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}grDataQuality"/>
 *       &lt;attribute name="Type" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}OrganisationInfoTypeList" />
 *       &lt;attribute name="CategoryType" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}OrganisationCategoryTypeList" />
 *       &lt;attribute name="Status" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}StatusList" />
 *       &lt;attribute name="Nature" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}OrganisationInfoNatureList" />
 *       &lt;attribute name="IndustryType" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}IndustryTypeList" />
 *       &lt;attribute name="IndustryCode" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil}IndustryCodeList" />
 *       &lt;attribute name="IndustryCodeType" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}String" />
 *       &lt;attribute name="NumberOfEmployees" type="{urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct}String" />
 *       &lt;attribute name="OperatingHourStartTime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="OperatingHourEndTime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrganisationInfo")
public class OrganisationInfo {

    @XmlAttribute(name = "Type", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "CategoryType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    protected OrganisationCategoryTypeList categoryType;
    @XmlAttribute(name = "Status", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    protected String status;
    @XmlAttribute(name = "Nature", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nature;
    @XmlAttribute(name = "IndustryType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String industryType;
    @XmlAttribute(name = "IndustryCode", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String industryCode;
    @XmlAttribute(name = "IndustryCodeType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String industryCodeType;
    @XmlAttribute(name = "NumberOfEmployees", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numberOfEmployees;
    @XmlAttribute(name = "OperatingHourStartTime", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar operatingHourStartTime;
    @XmlAttribute(name = "OperatingHourEndTime", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:xpil")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar operatingHourEndTime;
    @XmlAttribute(name = "DataQualityType", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct")
    protected DataQualityTypeList dataQualityType;
    @XmlAttribute(name = "ValidFrom", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFrom;
    @XmlAttribute(name = "ValidTo", namespace = "urn:oasis:names:tc:emergency:edxl:ciq:1.0:ct")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validTo;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the categoryType property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationCategoryTypeList }
     *     
     */
    public OrganisationCategoryTypeList getCategoryType() {
        return categoryType;
    }

    /**
     * Sets the value of the categoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationCategoryTypeList }
     *     
     */
    public void setCategoryType(OrganisationCategoryTypeList value) {
        this.categoryType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the nature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNature() {
        return nature;
    }

    /**
     * Sets the value of the nature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNature(String value) {
        this.nature = value;
    }

    /**
     * Gets the value of the industryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryType() {
        return industryType;
    }

    /**
     * Sets the value of the industryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryType(String value) {
        this.industryType = value;
    }

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCode(String value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the industryCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCodeType() {
        return industryCodeType;
    }

    /**
     * Sets the value of the industryCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCodeType(String value) {
        this.industryCodeType = value;
    }

    /**
     * Gets the value of the numberOfEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfEmployees() {
        return numberOfEmployees;
    }

    /**
     * Sets the value of the numberOfEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfEmployees(String value) {
        this.numberOfEmployees = value;
    }

    /**
     * Gets the value of the operatingHourStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperatingHourStartTime() {
        return operatingHourStartTime;
    }

    /**
     * Sets the value of the operatingHourStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperatingHourStartTime(XMLGregorianCalendar value) {
        this.operatingHourStartTime = value;
    }

    /**
     * Gets the value of the operatingHourEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperatingHourEndTime() {
        return operatingHourEndTime;
    }

    /**
     * Sets the value of the operatingHourEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperatingHourEndTime(XMLGregorianCalendar value) {
        this.operatingHourEndTime = value;
    }

    /**
     * Gets the value of the dataQualityType property.
     * 
     * @return
     *     possible object is
     *     {@link DataQualityTypeList }
     *     
     */
    public DataQualityTypeList getDataQualityType() {
        return dataQualityType;
    }

    /**
     * Sets the value of the dataQualityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataQualityTypeList }
     *     
     */
    public void setDataQualityType(DataQualityTypeList value) {
        this.dataQualityType = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
