//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.ct._1.ConfidenceDefaultType;
import oasis.names.tc.emergency.edxl.ct._1.ValueListType;


/**
 * <p>Java class for ConfidenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfidenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Confidence" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType"/>
 *         &lt;element name="ConfidenceDefault" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ConfidenceDefaultType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfidenceType", propOrder = {
    "confidence",
    "confidenceDefault"
})
public class ConfidenceType {

    @XmlElement(name = "Confidence")
    protected ValueListType confidence;
    @XmlElement(name = "ConfidenceDefault")
    protected ConfidenceDefaultType confidenceDefault;

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setConfidence(ValueListType value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the confidenceDefault property.
     * 
     * @return
     *     possible object is
     *     {@link ConfidenceDefaultType }
     *     
     */
    public ConfidenceDefaultType getConfidenceDefault() {
        return confidenceDefault;
    }

    /**
     * Sets the value of the confidenceDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfidenceDefaultType }
     *     
     */
    public void setConfidenceDefault(ConfidenceDefaultType value) {
        this.confidenceDefault = value;
    }

}
