//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalAffairsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalAffairsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EffectivePublicCommunication" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TalkingPoints">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TalkingPoint" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rumors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Rumor" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalAffairsType", propOrder = {
    "effectivePublicCommunication",
    "talkingPoints",
    "rumors"
})
public class ExternalAffairsType {

    @XmlElement(name = "EffectivePublicCommunication")
    protected Boolean effectivePublicCommunication;
    @XmlElement(name = "TalkingPoints", required = true)
    protected ExternalAffairsType.TalkingPoints talkingPoints;
    @XmlElement(name = "Rumors", required = true)
    protected ExternalAffairsType.Rumors rumors;

    /**
     * Gets the value of the effectivePublicCommunication property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEffectivePublicCommunication() {
        return effectivePublicCommunication;
    }

    /**
     * Sets the value of the effectivePublicCommunication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEffectivePublicCommunication(Boolean value) {
        this.effectivePublicCommunication = value;
    }

    /**
     * Gets the value of the talkingPoints property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalAffairsType.TalkingPoints }
     *     
     */
    public ExternalAffairsType.TalkingPoints getTalkingPoints() {
        return talkingPoints;
    }

    /**
     * Sets the value of the talkingPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalAffairsType.TalkingPoints }
     *     
     */
    public void setTalkingPoints(ExternalAffairsType.TalkingPoints value) {
        this.talkingPoints = value;
    }

    /**
     * Gets the value of the rumors property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalAffairsType.Rumors }
     *     
     */
    public ExternalAffairsType.Rumors getRumors() {
        return rumors;
    }

    /**
     * Sets the value of the rumors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalAffairsType.Rumors }
     *     
     */
    public void setRumors(ExternalAffairsType.Rumors value) {
        this.rumors = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Rumor" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rumor"
    })
    public static class Rumors {

        @XmlElement(name = "Rumor")
        protected List<String> rumor;

        /**
         * Gets the value of the rumor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rumor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRumor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRumor() {
            if (rumor == null) {
                rumor = new ArrayList<String>();
            }
            return this.rumor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TalkingPoint" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "talkingPoint"
    })
    public static class TalkingPoints {

        @XmlElement(name = "TalkingPoint")
        protected List<String> talkingPoint;

        /**
         * Gets the value of the talkingPoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the talkingPoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTalkingPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getTalkingPoint() {
            if (talkingPoint == null) {
                talkingPoint = new ArrayList<String>();
            }
            return this.talkingPoint;
        }

    }

}
