//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import oasis.names.tc.emergency.edxl.ct._1.EDXLLocationType;


/**
 * <p>Java class for IncidentInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncidentName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="IncidentType" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}IncidentTypeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentComplexity" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}ComplexityType" minOccurs="0"/>
 *         &lt;element name="IncidentStartDateTime" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
 *         &lt;element name="GeographicSize">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IncidentGeographicSize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                   &lt;element name="Estimate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EstimateType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DisasterInformation" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}DisasterInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentLocation" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLLocationType"/>
 *         &lt;element name="JurisdictionInformation" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}Jurisdiction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentStaging" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}StagingArea" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentInfoType", propOrder = {
    "incidentName",
    "incidentType",
    "incidentComplexity",
    "incidentStartDateTime",
    "geographicSize",
    "disasterInformation",
    "incidentLocation",
    "jurisdictionInformation",
    "incidentStaging"
})
public class IncidentInfoType {

    @XmlElement(name = "IncidentName", required = true)
    protected List<String> incidentName;
    @XmlElement(name = "IncidentType")
    protected List<IncidentTypeType> incidentType;
    @XmlElement(name = "IncidentComplexity")
    protected ComplexityType incidentComplexity;
    @XmlElement(name = "IncidentStartDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar incidentStartDateTime;
    @XmlElement(name = "GeographicSize", required = true)
    protected IncidentInfoType.GeographicSize geographicSize;
    @XmlElement(name = "DisasterInformation")
    protected List<DisasterInformation> disasterInformation;
    @XmlElement(name = "IncidentLocation", required = true)
    protected EDXLLocationType incidentLocation;
    @XmlElement(name = "JurisdictionInformation")
    protected List<Jurisdiction> jurisdictionInformation;
    @XmlElement(name = "IncidentStaging")
    protected List<StagingArea> incidentStaging;

    /**
     * Gets the value of the incidentName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIncidentName() {
        if (incidentName == null) {
            incidentName = new ArrayList<String>();
        }
        return this.incidentName;
    }

    /**
     * Gets the value of the incidentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentTypeType }
     * 
     * 
     */
    public List<IncidentTypeType> getIncidentType() {
        if (incidentType == null) {
            incidentType = new ArrayList<IncidentTypeType>();
        }
        return this.incidentType;
    }

    /**
     * Gets the value of the incidentComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexityType }
     *     
     */
    public ComplexityType getIncidentComplexity() {
        return incidentComplexity;
    }

    /**
     * Sets the value of the incidentComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexityType }
     *     
     */
    public void setIncidentComplexity(ComplexityType value) {
        this.incidentComplexity = value;
    }

    /**
     * Gets the value of the incidentStartDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIncidentStartDateTime() {
        return incidentStartDateTime;
    }

    /**
     * Sets the value of the incidentStartDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIncidentStartDateTime(XMLGregorianCalendar value) {
        this.incidentStartDateTime = value;
    }

    /**
     * Gets the value of the geographicSize property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentInfoType.GeographicSize }
     *     
     */
    public IncidentInfoType.GeographicSize getGeographicSize() {
        return geographicSize;
    }

    /**
     * Sets the value of the geographicSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentInfoType.GeographicSize }
     *     
     */
    public void setGeographicSize(IncidentInfoType.GeographicSize value) {
        this.geographicSize = value;
    }

    /**
     * Gets the value of the disasterInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disasterInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisasterInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisasterInformation }
     * 
     * 
     */
    public List<DisasterInformation> getDisasterInformation() {
        if (disasterInformation == null) {
            disasterInformation = new ArrayList<DisasterInformation>();
        }
        return this.disasterInformation;
    }

    /**
     * Gets the value of the incidentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EDXLLocationType }
     *     
     */
    public EDXLLocationType getIncidentLocation() {
        return incidentLocation;
    }

    /**
     * Sets the value of the incidentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXLLocationType }
     *     
     */
    public void setIncidentLocation(EDXLLocationType value) {
        this.incidentLocation = value;
    }

    /**
     * Gets the value of the jurisdictionInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jurisdictionInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJurisdictionInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Jurisdiction }
     * 
     * 
     */
    public List<Jurisdiction> getJurisdictionInformation() {
        if (jurisdictionInformation == null) {
            jurisdictionInformation = new ArrayList<Jurisdiction>();
        }
        return this.jurisdictionInformation;
    }

    /**
     * Gets the value of the incidentStaging property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentStaging property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentStaging().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StagingArea }
     * 
     * 
     */
    public List<StagingArea> getIncidentStaging() {
        if (incidentStaging == null) {
            incidentStaging = new ArrayList<StagingArea>();
        }
        return this.incidentStaging;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IncidentGeographicSize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *         &lt;element name="Estimate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EstimateType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incidentGeographicSize",
        "estimate"
    })
    public static class GeographicSize {

        @XmlElement(name = "IncidentGeographicSize")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger incidentGeographicSize;
        @XmlElement(name = "Estimate")
        protected Boolean estimate;

        /**
         * Gets the value of the incidentGeographicSize property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIncidentGeographicSize() {
            return incidentGeographicSize;
        }

        /**
         * Sets the value of the incidentGeographicSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIncidentGeographicSize(BigInteger value) {
            this.incidentGeographicSize = value;
        }

        /**
         * Gets the value of the estimate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isEstimate() {
            return estimate;
        }

        /**
         * Sets the value of the estimate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEstimate(Boolean value) {
            this.estimate = value;
        }

    }

}
