//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import oasis.names.tc.emergency.edxl.ct._1.ValueKeyStringPairType;


/**
 * <p>Java class for IncidentDecisionSupportInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentDecisionSupportInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProjectedIncidentActivity" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueKeyStringPairType" minOccurs="0"/>
 *         &lt;element name="ProjectedNumberToBeSheltered" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="CriticalResourceNeeds" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueKeyStringPairType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProjectedFinalIncidentSize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="AnticipatedCompletion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AnticipatedCompletionDate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
 *                   &lt;element name="Remarks" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}RemarksType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProjectedDemobilization">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProjectedDemobilizationStartDate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
 *                   &lt;element name="Remarks" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}RemarksType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EstimatedCosts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EstimatedCostsToDate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}CurrencyType" minOccurs="0"/>
 *                   &lt;element name="Estimate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EstimateType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProjectedCosts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProjectedFinalCosts" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}CurrencyType" minOccurs="0"/>
 *                   &lt;element name="Remarks" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}RemarksType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EmergencyResponseIssues" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}EmergencyResponseIssuesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StrategicDiscussion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlannedActions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentDecisionSupportInformation", propOrder = {
    "projectedIncidentActivity",
    "projectedNumberToBeSheltered",
    "criticalResourceNeeds",
    "projectedFinalIncidentSize",
    "anticipatedCompletion",
    "projectedDemobilization",
    "estimatedCosts",
    "projectedCosts",
    "emergencyResponseIssues",
    "strategicDiscussion",
    "plannedActions"
})
public class IncidentDecisionSupportInformation {

    @XmlElement(name = "ProjectedIncidentActivity")
    protected ValueKeyStringPairType projectedIncidentActivity;
    @XmlElement(name = "ProjectedNumberToBeSheltered")
    @XmlSchemaType(name = "unsignedInt")
    protected Long projectedNumberToBeSheltered;
    @XmlElement(name = "CriticalResourceNeeds")
    protected List<ValueKeyStringPairType> criticalResourceNeeds;
    @XmlElement(name = "ProjectedFinalIncidentSize")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger projectedFinalIncidentSize;
    @XmlElement(name = "AnticipatedCompletion", required = true)
    protected IncidentDecisionSupportInformation.AnticipatedCompletion anticipatedCompletion;
    @XmlElement(name = "ProjectedDemobilization", required = true)
    protected IncidentDecisionSupportInformation.ProjectedDemobilization projectedDemobilization;
    @XmlElement(name = "EstimatedCosts", required = true)
    protected IncidentDecisionSupportInformation.EstimatedCosts estimatedCosts;
    @XmlElement(name = "ProjectedCosts", required = true)
    protected IncidentDecisionSupportInformation.ProjectedCosts projectedCosts;
    @XmlElement(name = "EmergencyResponseIssues")
    protected List<EmergencyResponseIssuesType> emergencyResponseIssues;
    @XmlElement(name = "StrategicDiscussion")
    protected String strategicDiscussion;
    @XmlElement(name = "PlannedActions")
    protected String plannedActions;

    /**
     * Gets the value of the projectedIncidentActivity property.
     * 
     * @return
     *     possible object is
     *     {@link ValueKeyStringPairType }
     *     
     */
    public ValueKeyStringPairType getProjectedIncidentActivity() {
        return projectedIncidentActivity;
    }

    /**
     * Sets the value of the projectedIncidentActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueKeyStringPairType }
     *     
     */
    public void setProjectedIncidentActivity(ValueKeyStringPairType value) {
        this.projectedIncidentActivity = value;
    }

    /**
     * Gets the value of the projectedNumberToBeSheltered property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProjectedNumberToBeSheltered() {
        return projectedNumberToBeSheltered;
    }

    /**
     * Sets the value of the projectedNumberToBeSheltered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProjectedNumberToBeSheltered(Long value) {
        this.projectedNumberToBeSheltered = value;
    }

    /**
     * Gets the value of the criticalResourceNeeds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criticalResourceNeeds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCriticalResourceNeeds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueKeyStringPairType }
     * 
     * 
     */
    public List<ValueKeyStringPairType> getCriticalResourceNeeds() {
        if (criticalResourceNeeds == null) {
            criticalResourceNeeds = new ArrayList<ValueKeyStringPairType>();
        }
        return this.criticalResourceNeeds;
    }

    /**
     * Gets the value of the projectedFinalIncidentSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProjectedFinalIncidentSize() {
        return projectedFinalIncidentSize;
    }

    /**
     * Sets the value of the projectedFinalIncidentSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProjectedFinalIncidentSize(BigInteger value) {
        this.projectedFinalIncidentSize = value;
    }

    /**
     * Gets the value of the anticipatedCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentDecisionSupportInformation.AnticipatedCompletion }
     *     
     */
    public IncidentDecisionSupportInformation.AnticipatedCompletion getAnticipatedCompletion() {
        return anticipatedCompletion;
    }

    /**
     * Sets the value of the anticipatedCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentDecisionSupportInformation.AnticipatedCompletion }
     *     
     */
    public void setAnticipatedCompletion(IncidentDecisionSupportInformation.AnticipatedCompletion value) {
        this.anticipatedCompletion = value;
    }

    /**
     * Gets the value of the projectedDemobilization property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentDecisionSupportInformation.ProjectedDemobilization }
     *     
     */
    public IncidentDecisionSupportInformation.ProjectedDemobilization getProjectedDemobilization() {
        return projectedDemobilization;
    }

    /**
     * Sets the value of the projectedDemobilization property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentDecisionSupportInformation.ProjectedDemobilization }
     *     
     */
    public void setProjectedDemobilization(IncidentDecisionSupportInformation.ProjectedDemobilization value) {
        this.projectedDemobilization = value;
    }

    /**
     * Gets the value of the estimatedCosts property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentDecisionSupportInformation.EstimatedCosts }
     *     
     */
    public IncidentDecisionSupportInformation.EstimatedCosts getEstimatedCosts() {
        return estimatedCosts;
    }

    /**
     * Sets the value of the estimatedCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentDecisionSupportInformation.EstimatedCosts }
     *     
     */
    public void setEstimatedCosts(IncidentDecisionSupportInformation.EstimatedCosts value) {
        this.estimatedCosts = value;
    }

    /**
     * Gets the value of the projectedCosts property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentDecisionSupportInformation.ProjectedCosts }
     *     
     */
    public IncidentDecisionSupportInformation.ProjectedCosts getProjectedCosts() {
        return projectedCosts;
    }

    /**
     * Sets the value of the projectedCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentDecisionSupportInformation.ProjectedCosts }
     *     
     */
    public void setProjectedCosts(IncidentDecisionSupportInformation.ProjectedCosts value) {
        this.projectedCosts = value;
    }

    /**
     * Gets the value of the emergencyResponseIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emergencyResponseIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmergencyResponseIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmergencyResponseIssuesType }
     * 
     * 
     */
    public List<EmergencyResponseIssuesType> getEmergencyResponseIssues() {
        if (emergencyResponseIssues == null) {
            emergencyResponseIssues = new ArrayList<EmergencyResponseIssuesType>();
        }
        return this.emergencyResponseIssues;
    }

    /**
     * Gets the value of the strategicDiscussion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategicDiscussion() {
        return strategicDiscussion;
    }

    /**
     * Sets the value of the strategicDiscussion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategicDiscussion(String value) {
        this.strategicDiscussion = value;
    }

    /**
     * Gets the value of the plannedActions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedActions() {
        return plannedActions;
    }

    /**
     * Sets the value of the plannedActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedActions(String value) {
        this.plannedActions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AnticipatedCompletionDate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
     *         &lt;element name="Remarks" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}RemarksType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "anticipatedCompletionDate",
        "remarks"
    })
    public static class AnticipatedCompletion {

        @XmlElement(name = "AnticipatedCompletionDate")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar anticipatedCompletionDate;
        @XmlElement(name = "Remarks")
        protected String remarks;

        /**
         * Gets the value of the anticipatedCompletionDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAnticipatedCompletionDate() {
            return anticipatedCompletionDate;
        }

        /**
         * Sets the value of the anticipatedCompletionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAnticipatedCompletionDate(XMLGregorianCalendar value) {
            this.anticipatedCompletionDate = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EstimatedCostsToDate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}CurrencyType" minOccurs="0"/>
     *         &lt;element name="Estimate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EstimateType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estimatedCostsToDate",
        "estimate"
    })
    public static class EstimatedCosts {

        @XmlElement(name = "EstimatedCostsToDate")
        protected String estimatedCostsToDate;
        @XmlElement(name = "Estimate")
        protected Boolean estimate;

        /**
         * Gets the value of the estimatedCostsToDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstimatedCostsToDate() {
            return estimatedCostsToDate;
        }

        /**
         * Sets the value of the estimatedCostsToDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstimatedCostsToDate(String value) {
            this.estimatedCostsToDate = value;
        }

        /**
         * Gets the value of the estimate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isEstimate() {
            return estimate;
        }

        /**
         * Sets the value of the estimate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEstimate(Boolean value) {
            this.estimate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProjectedFinalCosts" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}CurrencyType" minOccurs="0"/>
     *         &lt;element name="Remarks" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}RemarksType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectedFinalCosts",
        "remarks"
    })
    public static class ProjectedCosts {

        @XmlElement(name = "ProjectedFinalCosts")
        protected String projectedFinalCosts;
        @XmlElement(name = "Remarks")
        protected String remarks;

        /**
         * Gets the value of the projectedFinalCosts property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProjectedFinalCosts() {
            return projectedFinalCosts;
        }

        /**
         * Sets the value of the projectedFinalCosts property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProjectedFinalCosts(String value) {
            this.projectedFinalCosts = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProjectedDemobilizationStartDate" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
     *         &lt;element name="Remarks" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}RemarksType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectedDemobilizationStartDate",
        "remarks"
    })
    public static class ProjectedDemobilization {

        @XmlElement(name = "ProjectedDemobilizationStartDate")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar projectedDemobilizationStartDate;
        @XmlElement(name = "Remarks")
        protected String remarks;

        /**
         * Gets the value of the projectedDemobilizationStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getProjectedDemobilizationStartDate() {
            return projectedDemobilizationStartDate;
        }

        /**
         * Sets the value of the projectedDemobilizationStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setProjectedDemobilizationStartDate(XMLGregorianCalendar value) {
            this.projectedDemobilizationStartDate = value;
        }

        /**
         * Gets the value of the remarks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * Sets the value of the remarks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemarks(String value) {
            this.remarks = value;
        }

    }

}
