//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.ct._1.IncidentTypeDefaultType;
import oasis.names.tc.emergency.edxl.ct._1.ValueListType;


/**
 * <p>Java class for IncidentTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="IncidentType" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType"/>
 *         &lt;element name="IncidentTypeDefault" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}IncidentTypeDefaultType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentTypeType", propOrder = {
    "incidentType",
    "incidentTypeDefault"
})
public class IncidentTypeType {

    @XmlElement(name = "IncidentType")
    protected ValueListType incidentType;
    @XmlElement(name = "IncidentTypeDefault")
    protected IncidentTypeDefaultType incidentTypeDefault;

    /**
     * Gets the value of the incidentType property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getIncidentType() {
        return incidentType;
    }

    /**
     * Sets the value of the incidentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setIncidentType(ValueListType value) {
        this.incidentType = value;
    }

    /**
     * Gets the value of the incidentTypeDefault property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentTypeDefaultType }
     *     
     */
    public IncidentTypeDefaultType getIncidentTypeDefault() {
        return incidentTypeDefault;
    }

    /**
     * Sets the value of the incidentTypeDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentTypeDefaultType }
     *     
     */
    public void setIncidentTypeDefault(IncidentTypeDefaultType value) {
        this.incidentTypeDefault = value;
    }

}
