//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.ct._1.LifeAndSafetyThreatDefaultType;
import oasis.names.tc.emergency.edxl.ct._1.ValueListType;


/**
 * <p>Java class for LifeAndSafetyThreatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LifeAndSafetyThreatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LifeAndSafetyThreat" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType"/>
 *         &lt;element name="LifeAndSafetyThreatDefault" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}LifeAndSafetyThreatDefaultType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LifeAndSafetyThreatType", propOrder = {
    "lifeAndSafetyThreat",
    "lifeAndSafetyThreatDefault"
})
public class LifeAndSafetyThreatType {

    @XmlElement(name = "LifeAndSafetyThreat")
    protected ValueListType lifeAndSafetyThreat;
    @XmlElement(name = "LifeAndSafetyThreatDefault")
    protected LifeAndSafetyThreatDefaultType lifeAndSafetyThreatDefault;

    /**
     * Gets the value of the lifeAndSafetyThreat property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getLifeAndSafetyThreat() {
        return lifeAndSafetyThreat;
    }

    /**
     * Sets the value of the lifeAndSafetyThreat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setLifeAndSafetyThreat(ValueListType value) {
        this.lifeAndSafetyThreat = value;
    }

    /**
     * Gets the value of the lifeAndSafetyThreatDefault property.
     * 
     * @return
     *     possible object is
     *     {@link LifeAndSafetyThreatDefaultType }
     *     
     */
    public LifeAndSafetyThreatDefaultType getLifeAndSafetyThreatDefault() {
        return lifeAndSafetyThreatDefault;
    }

    /**
     * Sets the value of the lifeAndSafetyThreatDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeAndSafetyThreatDefaultType }
     *     
     */
    public void setLifeAndSafetyThreatDefault(LifeAndSafetyThreatDefaultType value) {
        this.lifeAndSafetyThreatDefault = value;
    }

}
