//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.emergency.edxl.sitrep._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ManagementReportingSummary_QNAME = new QName("urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", "ManagementReportingSummary");
    private final static QName _ResponseResourcesTotals_QNAME = new QName("urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", "ResponseResourcesTotals");
    private final static QName _SituationInformation_QNAME = new QName("urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", "SituationInformation");
    private final static QName _FieldObservation_QNAME = new QName("urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", "FieldObservation");
    private final static QName _SitRep_QNAME = new QName("urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", "SitRep");
    private final static QName _CasualtyAndIllnessSummary_QNAME = new QName("urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", "CasualtyAndIllnessSummary");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.emergency.edxl.sitrep._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncidentDecisionSupportInformation }
     * 
     */
    public IncidentDecisionSupportInformation createIncidentDecisionSupportInformation() {
        return new IncidentDecisionSupportInformation();
    }

    /**
     * Create an instance of {@link ExternalAffairsType }
     * 
     */
    public ExternalAffairsType createExternalAffairsType() {
        return new ExternalAffairsType();
    }

    /**
     * Create an instance of {@link Jurisdiction }
     * 
     */
    public Jurisdiction createJurisdiction() {
        return new Jurisdiction();
    }

    /**
     * Create an instance of {@link IncidentInfoType }
     * 
     */
    public IncidentInfoType createIncidentInfoType() {
        return new IncidentInfoType();
    }

    /**
     * Create an instance of {@link SituationSummary }
     * 
     */
    public SituationSummary createSituationSummary() {
        return new SituationSummary();
    }

    /**
     * Create an instance of {@link CasualtyAndIllnessCategory }
     * 
     */
    public CasualtyAndIllnessCategory createCasualtyAndIllnessCategory() {
        return new CasualtyAndIllnessCategory();
    }

    /**
     * Create an instance of {@link SituationInformation }
     * 
     */
    public SituationInformation createSituationInformation() {
        return new SituationInformation();
    }

    /**
     * Create an instance of {@link SitRep }
     * 
     */
    public SitRep createSitRep() {
        return new SitRep();
    }

    /**
     * Create an instance of {@link FieldObservation }
     * 
     */
    public FieldObservation createFieldObservation() {
        return new FieldObservation();
    }

    /**
     * Create an instance of {@link ManagementReportingSummary }
     * 
     */
    public ManagementReportingSummary createManagementReportingSummary() {
        return new ManagementReportingSummary();
    }

    /**
     * Create an instance of {@link ResponseResourcesTotals }
     * 
     */
    public ResponseResourcesTotals createResponseResourcesTotals() {
        return new ResponseResourcesTotals();
    }

    /**
     * Create an instance of {@link CasualtyAndIllnessSummary }
     * 
     */
    public CasualtyAndIllnessSummary createCasualtyAndIllnessSummary() {
        return new CasualtyAndIllnessSummary();
    }

    /**
     * Create an instance of {@link CommandOrganization }
     * 
     */
    public CommandOrganization createCommandOrganization() {
        return new CommandOrganization();
    }

    /**
     * Create an instance of {@link CasualtyAndIllnessCountCategoryType }
     * 
     */
    public CasualtyAndIllnessCountCategoryType createCasualtyAndIllnessCountCategoryType() {
        return new CasualtyAndIllnessCountCategoryType();
    }

    /**
     * Create an instance of {@link ReportVersionType }
     * 
     */
    public ReportVersionType createReportVersionType() {
        return new ReportVersionType();
    }

    /**
     * Create an instance of {@link ResponseResourceTotals }
     * 
     */
    public ResponseResourceTotals createResponseResourceTotals() {
        return new ResponseResourceTotals();
    }

    /**
     * Create an instance of {@link SignificantEventsType }
     * 
     */
    public SignificantEventsType createSignificantEventsType() {
        return new SignificantEventsType();
    }

    /**
     * Create an instance of {@link ConfidenceType }
     * 
     */
    public ConfidenceType createConfidenceType() {
        return new ConfidenceType();
    }

    /**
     * Create an instance of {@link SeverityType }
     * 
     */
    public SeverityType createSeverityType() {
        return new SeverityType();
    }

    /**
     * Create an instance of {@link EmergencyResponseIssuesType }
     * 
     */
    public EmergencyResponseIssuesType createEmergencyResponseIssuesType() {
        return new EmergencyResponseIssuesType();
    }

    /**
     * Create an instance of {@link ImmediateNeedsCategoryType }
     * 
     */
    public ImmediateNeedsCategoryType createImmediateNeedsCategoryType() {
        return new ImmediateNeedsCategoryType();
    }

    /**
     * Create an instance of {@link DisasterInformation }
     * 
     */
    public DisasterInformation createDisasterInformation() {
        return new DisasterInformation();
    }

    /**
     * Create an instance of {@link NotifiableDiseaseNumbers }
     * 
     */
    public NotifiableDiseaseNumbers createNotifiableDiseaseNumbers() {
        return new NotifiableDiseaseNumbers();
    }

    /**
     * Create an instance of {@link DebrisManagementType }
     * 
     */
    public DebrisManagementType createDebrisManagementType() {
        return new DebrisManagementType();
    }

    /**
     * Create an instance of {@link StagingArea }
     * 
     */
    public StagingArea createStagingArea() {
        return new StagingArea();
    }

    /**
     * Create an instance of {@link IncidentLifecycleType }
     * 
     */
    public IncidentLifecycleType createIncidentLifecycleType() {
        return new IncidentLifecycleType();
    }

    /**
     * Create an instance of {@link InfrastructureAffectedType }
     * 
     */
    public InfrastructureAffectedType createInfrastructureAffectedType() {
        return new InfrastructureAffectedType();
    }

    /**
     * Create an instance of {@link PropertyDamageType }
     * 
     */
    public PropertyDamageType createPropertyDamageType() {
        return new PropertyDamageType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link UrgencyType }
     * 
     */
    public UrgencyType createUrgencyType() {
        return new UrgencyType();
    }

    /**
     * Create an instance of {@link LifeAndSafetyThreatType }
     * 
     */
    public LifeAndSafetyThreatType createLifeAndSafetyThreatType() {
        return new LifeAndSafetyThreatType();
    }

    /**
     * Create an instance of {@link ResponseResourcesDetail }
     * 
     */
    public ResponseResourcesDetail createResponseResourcesDetail() {
        return new ResponseResourcesDetail();
    }

    /**
     * Create an instance of {@link ResourceCount }
     * 
     */
    public ResourceCount createResourceCount() {
        return new ResourceCount();
    }

    /**
     * Create an instance of {@link IncidentTypeType }
     * 
     */
    public IncidentTypeType createIncidentTypeType() {
        return new IncidentTypeType();
    }

    /**
     * Create an instance of {@link ResourceStatusType }
     * 
     */
    public ResourceStatusType createResourceStatusType() {
        return new ResourceStatusType();
    }

    /**
     * Create an instance of {@link ComplexityType }
     * 
     */
    public ComplexityType createComplexityType() {
        return new ComplexityType();
    }

    /**
     * Create an instance of {@link IncidentDecisionSupportInformation.AnticipatedCompletion }
     * 
     */
    public IncidentDecisionSupportInformation.AnticipatedCompletion createIncidentDecisionSupportInformationAnticipatedCompletion() {
        return new IncidentDecisionSupportInformation.AnticipatedCompletion();
    }

    /**
     * Create an instance of {@link IncidentDecisionSupportInformation.ProjectedDemobilization }
     * 
     */
    public IncidentDecisionSupportInformation.ProjectedDemobilization createIncidentDecisionSupportInformationProjectedDemobilization() {
        return new IncidentDecisionSupportInformation.ProjectedDemobilization();
    }

    /**
     * Create an instance of {@link IncidentDecisionSupportInformation.EstimatedCosts }
     * 
     */
    public IncidentDecisionSupportInformation.EstimatedCosts createIncidentDecisionSupportInformationEstimatedCosts() {
        return new IncidentDecisionSupportInformation.EstimatedCosts();
    }

    /**
     * Create an instance of {@link IncidentDecisionSupportInformation.ProjectedCosts }
     * 
     */
    public IncidentDecisionSupportInformation.ProjectedCosts createIncidentDecisionSupportInformationProjectedCosts() {
        return new IncidentDecisionSupportInformation.ProjectedCosts();
    }

    /**
     * Create an instance of {@link ExternalAffairsType.TalkingPoints }
     * 
     */
    public ExternalAffairsType.TalkingPoints createExternalAffairsTypeTalkingPoints() {
        return new ExternalAffairsType.TalkingPoints();
    }

    /**
     * Create an instance of {@link ExternalAffairsType.Rumors }
     * 
     */
    public ExternalAffairsType.Rumors createExternalAffairsTypeRumors() {
        return new ExternalAffairsType.Rumors();
    }

    /**
     * Create an instance of {@link Jurisdiction.JurisdictionSize }
     * 
     */
    public Jurisdiction.JurisdictionSize createJurisdictionJurisdictionSize() {
        return new Jurisdiction.JurisdictionSize();
    }

    /**
     * Create an instance of {@link IncidentInfoType.GeographicSize }
     * 
     */
    public IncidentInfoType.GeographicSize createIncidentInfoTypeGeographicSize() {
        return new IncidentInfoType.GeographicSize();
    }

    /**
     * Create an instance of {@link SituationSummary.HazMatIncidentReport }
     * 
     */
    public SituationSummary.HazMatIncidentReport createSituationSummaryHazMatIncidentReport() {
        return new SituationSummary.HazMatIncidentReport();
    }

    /**
     * Create an instance of {@link CasualtyAndIllnessCategory.ReceivedMassImmunizations }
     * 
     */
    public CasualtyAndIllnessCategory.ReceivedMassImmunizations createCasualtyAndIllnessCategoryReceivedMassImmunizations() {
        return new CasualtyAndIllnessCategory.ReceivedMassImmunizations();
    }

    /**
     * Create an instance of {@link CasualtyAndIllnessCategory.RequireMassImmunizations }
     * 
     */
    public CasualtyAndIllnessCategory.RequireMassImmunizations createCasualtyAndIllnessCategoryRequireMassImmunizations() {
        return new CasualtyAndIllnessCategory.RequireMassImmunizations();
    }

    /**
     * Create an instance of {@link SituationInformation.SubIncidentInformation }
     * 
     */
    public SituationInformation.SubIncidentInformation createSituationInformationSubIncidentInformation() {
        return new SituationInformation.SubIncidentInformation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManagementReportingSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", name = "ManagementReportingSummary")
    public JAXBElement<ManagementReportingSummary> createManagementReportingSummary(ManagementReportingSummary value) {
        return new JAXBElement<ManagementReportingSummary>(_ManagementReportingSummary_QNAME, ManagementReportingSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseResourcesTotals }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", name = "ResponseResourcesTotals")
    public JAXBElement<ResponseResourcesTotals> createResponseResourcesTotals(ResponseResourcesTotals value) {
        return new JAXBElement<ResponseResourcesTotals>(_ResponseResourcesTotals_QNAME, ResponseResourcesTotals.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SituationInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", name = "SituationInformation")
    public JAXBElement<SituationInformation> createSituationInformation(SituationInformation value) {
        return new JAXBElement<SituationInformation>(_SituationInformation_QNAME, SituationInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldObservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", name = "FieldObservation")
    public JAXBElement<FieldObservation> createFieldObservation(FieldObservation value) {
        return new JAXBElement<FieldObservation>(_FieldObservation_QNAME, FieldObservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SitRep }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", name = "SitRep")
    public JAXBElement<SitRep> createSitRep(SitRep value) {
        return new JAXBElement<SitRep>(_SitRep_QNAME, SitRep.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CasualtyAndIllnessSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:emergency:EDXL:SitRep:1.0", name = "CasualtyAndIllnessSummary")
    public JAXBElement<CasualtyAndIllnessSummary> createCasualtyAndIllnessSummary(CasualtyAndIllnessSummary value) {
        return new JAXBElement<CasualtyAndIllnessSummary>(_CasualtyAndIllnessSummary_QNAME, CasualtyAndIllnessSummary.class, null, value);
    }

}
