//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.ct._1.ReportVersionDefaultType;
import oasis.names.tc.emergency.edxl.ct._1.ValueListType;


/**
 * <p>Java class for ReportVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportVersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Version" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType"/>
 *         &lt;element name="VersionDefault" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ReportVersionDefaultType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportVersionType", propOrder = {
    "version",
    "versionDefault"
})
public class ReportVersionType {

    @XmlElement(name = "Version")
    protected ValueListType version;
    @XmlElement(name = "VersionDefault")
    protected ReportVersionDefaultType versionDefault;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setVersion(ValueListType value) {
        this.version = value;
    }

    /**
     * Gets the value of the versionDefault property.
     * 
     * @return
     *     possible object is
     *     {@link ReportVersionDefaultType }
     *     
     */
    public ReportVersionDefaultType getVersionDefault() {
        return versionDefault;
    }

    /**
     * Sets the value of the versionDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportVersionDefaultType }
     *     
     */
    public void setVersionDefault(ReportVersionDefaultType value) {
        this.versionDefault = value;
    }

}
