//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import oasis.names.tc.emergency.edxl.ct._1.ValueListType;


/**
 * <p>Java class for ResourceCount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceCount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgencyOrganization" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType"/>
 *         &lt;element name="ResourceName" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType"/>
 *         &lt;element name="ResourceTypeCategoryKind" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType" minOccurs="0"/>
 *         &lt;element name="ResourceDetail" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}ResponseResourcesDetail" minOccurs="0"/>
 *         &lt;element name="IsSufficient" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceCount", propOrder = {
    "agencyOrganization",
    "resourceName",
    "resourceTypeCategoryKind",
    "resourceDetail",
    "isSufficient"
})
public class ResourceCount {

    @XmlElement(name = "AgencyOrganization", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String agencyOrganization;
    @XmlElement(name = "ResourceName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String resourceName;
    @XmlElement(name = "ResourceTypeCategoryKind")
    protected ValueListType resourceTypeCategoryKind;
    @XmlElement(name = "ResourceDetail")
    protected ResponseResourcesDetail resourceDetail;
    @XmlElement(name = "IsSufficient")
    protected Boolean isSufficient;

    /**
     * Gets the value of the agencyOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencyOrganization() {
        return agencyOrganization;
    }

    /**
     * Sets the value of the agencyOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencyOrganization(String value) {
        this.agencyOrganization = value;
    }

    /**
     * Gets the value of the resourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * Sets the value of the resourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceName(String value) {
        this.resourceName = value;
    }

    /**
     * Gets the value of the resourceTypeCategoryKind property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getResourceTypeCategoryKind() {
        return resourceTypeCategoryKind;
    }

    /**
     * Sets the value of the resourceTypeCategoryKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setResourceTypeCategoryKind(ValueListType value) {
        this.resourceTypeCategoryKind = value;
    }

    /**
     * Gets the value of the resourceDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseResourcesDetail }
     *     
     */
    public ResponseResourcesDetail getResourceDetail() {
        return resourceDetail;
    }

    /**
     * Sets the value of the resourceDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseResourcesDetail }
     *     
     */
    public void setResourceDetail(ResponseResourcesDetail value) {
        this.resourceDetail = value;
    }

    /**
     * Gets the value of the isSufficient property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSufficient() {
        return isSufficient;
    }

    /**
     * Sets the value of the isSufficient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSufficient(Boolean value) {
        this.isSufficient = value;
    }

}
