//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import oasis.names.tc.emergency.edxl.ct._1.EDXLLocationType;
import oasis.names.tc.emergency.edxl.ct._1.ValueKeyIntPairType;


/**
 * <p>Java class for ResponseResourcesDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseResourcesDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourcePersonnelCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="UnassignedResourcePersonnel" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ResourceRequiredCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ResourceCommittedCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ResourceOnHandCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ResourceStillNeededCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="ResourceRequestedCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="DateTimeOrdered" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
 *         &lt;element name="RequestedArrival" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
 *         &lt;element name="EstimatedArrival" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLDateTimeType" minOccurs="0"/>
 *         &lt;element name="ReportToLocation" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLLocationType" minOccurs="0"/>
 *         &lt;element name="OverheadPosition" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueKeyIntPairType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WorkAssignment" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLStringType" minOccurs="0"/>
 *         &lt;element name="SpecialInstructions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SpecialEquipmentAndSupplies" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdditionalAssistingOrganizations" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResourceStatus" type="{urn:oasis:names:tc:emergency:EDXL:SitRep:1.0}ResourceStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseResourcesDetail", propOrder = {
    "resourcePersonnelCount",
    "unassignedResourcePersonnel",
    "resourceRequiredCount",
    "resourceCommittedCount",
    "resourceOnHandCount",
    "resourceStillNeededCount",
    "resourceRequestedCount",
    "dateTimeOrdered",
    "requestedArrival",
    "estimatedArrival",
    "reportToLocation",
    "overheadPosition",
    "workAssignment",
    "specialInstructions",
    "specialEquipmentAndSupplies",
    "additionalAssistingOrganizations",
    "resourceStatus"
})
public class ResponseResourcesDetail {

    @XmlElement(name = "ResourcePersonnelCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long resourcePersonnelCount;
    @XmlElement(name = "UnassignedResourcePersonnel")
    @XmlSchemaType(name = "unsignedInt")
    protected Long unassignedResourcePersonnel;
    @XmlElement(name = "ResourceRequiredCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long resourceRequiredCount;
    @XmlElement(name = "ResourceCommittedCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long resourceCommittedCount;
    @XmlElement(name = "ResourceOnHandCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long resourceOnHandCount;
    @XmlElement(name = "ResourceStillNeededCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long resourceStillNeededCount;
    @XmlElement(name = "ResourceRequestedCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long resourceRequestedCount;
    @XmlElement(name = "DateTimeOrdered")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeOrdered;
    @XmlElement(name = "RequestedArrival")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestedArrival;
    @XmlElement(name = "EstimatedArrival")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar estimatedArrival;
    @XmlElement(name = "ReportToLocation")
    protected EDXLLocationType reportToLocation;
    @XmlElement(name = "OverheadPosition")
    protected List<ValueKeyIntPairType> overheadPosition;
    @XmlElement(name = "WorkAssignment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String workAssignment;
    @XmlElement(name = "SpecialInstructions")
    protected String specialInstructions;
    @XmlElement(name = "SpecialEquipmentAndSupplies")
    protected List<String> specialEquipmentAndSupplies;
    @XmlElement(name = "AdditionalAssistingOrganizations")
    protected String additionalAssistingOrganizations;
    @XmlElement(name = "ResourceStatus")
    protected ResourceStatusType resourceStatus;

    /**
     * Gets the value of the resourcePersonnelCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResourcePersonnelCount() {
        return resourcePersonnelCount;
    }

    /**
     * Sets the value of the resourcePersonnelCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResourcePersonnelCount(Long value) {
        this.resourcePersonnelCount = value;
    }

    /**
     * Gets the value of the unassignedResourcePersonnel property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUnassignedResourcePersonnel() {
        return unassignedResourcePersonnel;
    }

    /**
     * Sets the value of the unassignedResourcePersonnel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUnassignedResourcePersonnel(Long value) {
        this.unassignedResourcePersonnel = value;
    }

    /**
     * Gets the value of the resourceRequiredCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResourceRequiredCount() {
        return resourceRequiredCount;
    }

    /**
     * Sets the value of the resourceRequiredCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResourceRequiredCount(Long value) {
        this.resourceRequiredCount = value;
    }

    /**
     * Gets the value of the resourceCommittedCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResourceCommittedCount() {
        return resourceCommittedCount;
    }

    /**
     * Sets the value of the resourceCommittedCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResourceCommittedCount(Long value) {
        this.resourceCommittedCount = value;
    }

    /**
     * Gets the value of the resourceOnHandCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResourceOnHandCount() {
        return resourceOnHandCount;
    }

    /**
     * Sets the value of the resourceOnHandCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResourceOnHandCount(Long value) {
        this.resourceOnHandCount = value;
    }

    /**
     * Gets the value of the resourceStillNeededCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResourceStillNeededCount() {
        return resourceStillNeededCount;
    }

    /**
     * Sets the value of the resourceStillNeededCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResourceStillNeededCount(Long value) {
        this.resourceStillNeededCount = value;
    }

    /**
     * Gets the value of the resourceRequestedCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getResourceRequestedCount() {
        return resourceRequestedCount;
    }

    /**
     * Sets the value of the resourceRequestedCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setResourceRequestedCount(Long value) {
        this.resourceRequestedCount = value;
    }

    /**
     * Gets the value of the dateTimeOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeOrdered() {
        return dateTimeOrdered;
    }

    /**
     * Sets the value of the dateTimeOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeOrdered(XMLGregorianCalendar value) {
        this.dateTimeOrdered = value;
    }

    /**
     * Gets the value of the requestedArrival property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestedArrival() {
        return requestedArrival;
    }

    /**
     * Sets the value of the requestedArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestedArrival(XMLGregorianCalendar value) {
        this.requestedArrival = value;
    }

    /**
     * Gets the value of the estimatedArrival property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEstimatedArrival() {
        return estimatedArrival;
    }

    /**
     * Sets the value of the estimatedArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEstimatedArrival(XMLGregorianCalendar value) {
        this.estimatedArrival = value;
    }

    /**
     * Gets the value of the reportToLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EDXLLocationType }
     *     
     */
    public EDXLLocationType getReportToLocation() {
        return reportToLocation;
    }

    /**
     * Sets the value of the reportToLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXLLocationType }
     *     
     */
    public void setReportToLocation(EDXLLocationType value) {
        this.reportToLocation = value;
    }

    /**
     * Gets the value of the overheadPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overheadPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverheadPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueKeyIntPairType }
     * 
     * 
     */
    public List<ValueKeyIntPairType> getOverheadPosition() {
        if (overheadPosition == null) {
            overheadPosition = new ArrayList<ValueKeyIntPairType>();
        }
        return this.overheadPosition;
    }

    /**
     * Gets the value of the workAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkAssignment() {
        return workAssignment;
    }

    /**
     * Sets the value of the workAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkAssignment(String value) {
        this.workAssignment = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstructions(String value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the specialEquipmentAndSupplies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialEquipmentAndSupplies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialEquipmentAndSupplies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecialEquipmentAndSupplies() {
        if (specialEquipmentAndSupplies == null) {
            specialEquipmentAndSupplies = new ArrayList<String>();
        }
        return this.specialEquipmentAndSupplies;
    }

    /**
     * Gets the value of the additionalAssistingOrganizations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalAssistingOrganizations() {
        return additionalAssistingOrganizations;
    }

    /**
     * Sets the value of the additionalAssistingOrganizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalAssistingOrganizations(String value) {
        this.additionalAssistingOrganizations = value;
    }

    /**
     * Gets the value of the resourceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceStatusType }
     *     
     */
    public ResourceStatusType getResourceStatus() {
        return resourceStatus;
    }

    /**
     * Sets the value of the resourceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceStatusType }
     *     
     */
    public void setResourceStatus(ResourceStatusType value) {
        this.resourceStatus = value;
    }

}
