//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.sitrep._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.ct._1.UrgencyDefaultType;
import oasis.names.tc.emergency.edxl.ct._1.ValueListType;


/**
 * <p>Java class for UrgencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UrgencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Urgency" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueListType"/>
 *         &lt;element name="UrgencyDefault" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}UrgencyDefaultType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UrgencyType", propOrder = {
    "urgency",
    "urgencyDefault"
})
public class UrgencyType {

    @XmlElement(name = "Urgency")
    protected ValueListType urgency;
    @XmlElement(name = "UrgencyDefault")
    protected UrgencyDefaultType urgencyDefault;

    /**
     * Gets the value of the urgency property.
     * 
     * @return
     *     possible object is
     *     {@link ValueListType }
     *     
     */
    public ValueListType getUrgency() {
        return urgency;
    }

    /**
     * Sets the value of the urgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueListType }
     *     
     */
    public void setUrgency(ValueListType value) {
        this.urgency = value;
    }

    /**
     * Gets the value of the urgencyDefault property.
     * 
     * @return
     *     possible object is
     *     {@link UrgencyDefaultType }
     *     
     */
    public UrgencyDefaultType getUrgencyDefault() {
        return urgencyDefault;
    }

    /**
     * Sets the value of the urgencyDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrgencyDefaultType }
     *     
     */
    public void setUrgencyDefault(UrgencyDefaultType value) {
        this.urgencyDefault = value;
    }

}
