//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 05:44:00 PM EET 
//


package oasis.names.tc.emergency.edxl.have._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  The container of all of the elements related to the emergency department status. It describes the ability of this emergency department to treat patients.
 * 
 * <p>Java class for EmergencyDepartmentStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmergencyDepartmentStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EMSTraffic" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EMSTrafficStatus" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Normal"/>
 *                         &lt;enumeration value="Advisory"/>
 *                         &lt;enumeration value="Closed"/>
 *                         &lt;enumeration value="NotApplicable"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EMSTrafficReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EMSCapacity" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}TriageCount" minOccurs="0"/>
 *         &lt;element name="EMSCensus" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}TriageCount" minOccurs="0"/>
 *         &lt;element name="EMSAmbulanceStatus" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}Offload" minOccurs="0"/>
 *         &lt;element name="EMSAirTransportStatus" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}Offload" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmergencyDepartmentStatus", propOrder = {
    "emsTraffic",
    "emsCapacity",
    "emsCensus",
    "emsAmbulanceStatus",
    "emsAirTransportStatus",
    "commentText"
})
public class EmergencyDepartmentStatus {

    @XmlElement(name = "EMSTraffic")
    protected EmergencyDepartmentStatus.EMSTraffic emsTraffic;
    @XmlElement(name = "EMSCapacity")
    protected TriageCount emsCapacity;
    @XmlElement(name = "EMSCensus")
    protected TriageCount emsCensus;
    @XmlElement(name = "EMSAmbulanceStatus")
    protected Offload emsAmbulanceStatus;
    @XmlElement(name = "EMSAirTransportStatus")
    protected Offload emsAirTransportStatus;
    @XmlElement(name = "CommentText")
    protected List<String> commentText;

    /**
     * Gets the value of the emsTraffic property.
     * 
     * @return
     *     possible object is
     *     {@link EmergencyDepartmentStatus.EMSTraffic }
     *     
     */
    public EmergencyDepartmentStatus.EMSTraffic getEMSTraffic() {
        return emsTraffic;
    }

    /**
     * Sets the value of the emsTraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmergencyDepartmentStatus.EMSTraffic }
     *     
     */
    public void setEMSTraffic(EmergencyDepartmentStatus.EMSTraffic value) {
        this.emsTraffic = value;
    }

    /**
     * Gets the value of the emsCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link TriageCount }
     *     
     */
    public TriageCount getEMSCapacity() {
        return emsCapacity;
    }

    /**
     * Sets the value of the emsCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriageCount }
     *     
     */
    public void setEMSCapacity(TriageCount value) {
        this.emsCapacity = value;
    }

    /**
     * Gets the value of the emsCensus property.
     * 
     * @return
     *     possible object is
     *     {@link TriageCount }
     *     
     */
    public TriageCount getEMSCensus() {
        return emsCensus;
    }

    /**
     * Sets the value of the emsCensus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TriageCount }
     *     
     */
    public void setEMSCensus(TriageCount value) {
        this.emsCensus = value;
    }

    /**
     * Gets the value of the emsAmbulanceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Offload }
     *     
     */
    public Offload getEMSAmbulanceStatus() {
        return emsAmbulanceStatus;
    }

    /**
     * Sets the value of the emsAmbulanceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offload }
     *     
     */
    public void setEMSAmbulanceStatus(Offload value) {
        this.emsAmbulanceStatus = value;
    }

    /**
     * Gets the value of the emsAirTransportStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Offload }
     *     
     */
    public Offload getEMSAirTransportStatus() {
        return emsAirTransportStatus;
    }

    /**
     * Sets the value of the emsAirTransportStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offload }
     *     
     */
    public void setEMSAirTransportStatus(Offload value) {
        this.emsAirTransportStatus = value;
    }

    /**
     * Gets the value of the commentText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCommentText() {
        if (commentText == null) {
            commentText = new ArrayList<String>();
        }
        return this.commentText;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EMSTrafficStatus" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Normal"/>
     *               &lt;enumeration value="Advisory"/>
     *               &lt;enumeration value="Closed"/>
     *               &lt;enumeration value="NotApplicable"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EMSTrafficReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emsTrafficStatus",
        "emsTrafficReason",
        "commentText"
    })
    public static class EMSTraffic {

        @XmlElement(name = "EMSTrafficStatus")
        protected String emsTrafficStatus;
        @XmlElement(name = "EMSTrafficReason")
        protected String emsTrafficReason;
        @XmlElement(name = "CommentText")
        protected String commentText;

        /**
         * Gets the value of the emsTrafficStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMSTrafficStatus() {
            return emsTrafficStatus;
        }

        /**
         * Sets the value of the emsTrafficStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMSTrafficStatus(String value) {
            this.emsTrafficStatus = value;
        }

        /**
         * Gets the value of the emsTrafficReason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMSTrafficReason() {
            return emsTrafficReason;
        }

        /**
         * Sets the value of the emsTrafficReason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMSTrafficReason(String value) {
            this.emsTrafficReason = value;
        }

        /**
         * Gets the value of the commentText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommentText() {
            return commentText;
        }

        /**
         * Sets the value of the commentText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommentText(String value) {
            this.commentText = value;
        }

    }

}
