//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 05:44:00 PM EET 
//


package oasis.names.tc.emergency.edxl.have._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The container of all of the elements related to the hospital bed capacity and status. For each of the bed types (AdultICU, MedicalSurgical, etc.), if needed, a collection of named sub-types can be provided. The totals of sub-categories SHOULD equal the capacity data specified in the parent.  
 * 
 * 
 * <p>Java class for HospitalBedCapacityStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HospitalBedCapacityStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BedCapacity" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BedType" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="AdultICU"/>
 *                         &lt;enumeration value="PediatricICU"/>
 *                         &lt;enumeration value="NeonatalICU"/>
 *                         &lt;enumeration value="EmergencyDepartment"/>
 *                         &lt;enumeration value="NurseryBeds"/>
 *                         &lt;enumeration value="MedicalSurgical"/>
 *                         &lt;enumeration value="RehabLongTermCare"/>
 *                         &lt;enumeration value="Burn"/>
 *                         &lt;enumeration value="Pediatrics"/>
 *                         &lt;enumeration value="AdultPsychiatric"/>
 *                         &lt;enumeration value="PediatricPsychiatric"/>
 *                         &lt;enumeration value="NegativeFlowIsolation"/>
 *                         &lt;enumeration value="OtherIsolation"/>
 *                         &lt;enumeration value="OperatingRooms"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SubCategoryBedType" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Capacity" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}Capacity" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HospitalBedCapacityStatus", propOrder = {
    "bedCapacity"
})
public class HospitalBedCapacityStatus {

    @XmlElement(name = "BedCapacity", required = true)
    protected List<HospitalBedCapacityStatus.BedCapacity> bedCapacity;

    /**
     * Gets the value of the bedCapacity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bedCapacity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBedCapacity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HospitalBedCapacityStatus.BedCapacity }
     * 
     * 
     */
    public List<HospitalBedCapacityStatus.BedCapacity> getBedCapacity() {
        if (bedCapacity == null) {
            bedCapacity = new ArrayList<HospitalBedCapacityStatus.BedCapacity>();
        }
        return this.bedCapacity;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BedType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="AdultICU"/>
     *               &lt;enumeration value="PediatricICU"/>
     *               &lt;enumeration value="NeonatalICU"/>
     *               &lt;enumeration value="EmergencyDepartment"/>
     *               &lt;enumeration value="NurseryBeds"/>
     *               &lt;enumeration value="MedicalSurgical"/>
     *               &lt;enumeration value="RehabLongTermCare"/>
     *               &lt;enumeration value="Burn"/>
     *               &lt;enumeration value="Pediatrics"/>
     *               &lt;enumeration value="AdultPsychiatric"/>
     *               &lt;enumeration value="PediatricPsychiatric"/>
     *               &lt;enumeration value="NegativeFlowIsolation"/>
     *               &lt;enumeration value="OtherIsolation"/>
     *               &lt;enumeration value="OperatingRooms"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SubCategoryBedType" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Capacity" type="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}Capacity" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bedType",
        "subCategoryBedType",
        "capacity",
        "commentText"
    })
    public static class BedCapacity {

        @XmlElement(name = "BedType")
        protected List<String> bedType;
        @XmlElement(name = "SubCategoryBedType")
        protected List<Object> subCategoryBedType;
        @XmlElement(name = "Capacity")
        protected List<Capacity> capacity;
        @XmlElement(name = "CommentText")
        protected List<String> commentText;

        /**
         * Gets the value of the bedType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bedType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBedType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getBedType() {
            if (bedType == null) {
                bedType = new ArrayList<String>();
            }
            return this.bedType;
        }

        /**
         * Gets the value of the subCategoryBedType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subCategoryBedType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubCategoryBedType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getSubCategoryBedType() {
            if (subCategoryBedType == null) {
                subCategoryBedType = new ArrayList<Object>();
            }
            return this.subCategoryBedType;
        }

        /**
         * Gets the value of the capacity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the capacity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCapacity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Capacity }
         * 
         * 
         */
        public List<Capacity> getCapacity() {
            if (capacity == null) {
                capacity = new ArrayList<Capacity>();
            }
            return this.capacity;
        }

        /**
         * Gets the value of the commentText property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the commentText property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCommentText().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCommentText() {
            if (commentText == null) {
                commentText = new ArrayList<String>();
            }
            return this.commentText;
        }

    }

}
