//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 05:44:00 PM EET 
//


package oasis.names.tc.emergency.edxl.have._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The container for all the elements related to the operations of the facility.  
 * 
 * <p>Java class for HospitalResourcesStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HospitalResourcesStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Staffing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Adequate"/>
 *               &lt;enumeration value="Insufficient"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FacilityOperations" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Adequate"/>
 *               &lt;enumeration value="Insufficient"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClinicalOperations" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Adequate"/>
 *               &lt;enumeration value="Insufficient"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ResourcesInformationText" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HospitalResourcesStatus", propOrder = {
    "staffing",
    "facilityOperations",
    "clinicalOperations",
    "resourcesInformationText",
    "commentText"
})
public class HospitalResourcesStatus {

    @XmlElement(name = "Staffing")
    protected String staffing;
    @XmlElement(name = "FacilityOperations")
    protected String facilityOperations;
    @XmlElement(name = "ClinicalOperations")
    protected String clinicalOperations;
    @XmlElement(name = "ResourcesInformationText")
    protected List<Object> resourcesInformationText;
    @XmlElement(name = "CommentText")
    protected List<String> commentText;

    /**
     * Gets the value of the staffing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaffing() {
        return staffing;
    }

    /**
     * Sets the value of the staffing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaffing(String value) {
        this.staffing = value;
    }

    /**
     * Gets the value of the facilityOperations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityOperations() {
        return facilityOperations;
    }

    /**
     * Sets the value of the facilityOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityOperations(String value) {
        this.facilityOperations = value;
    }

    /**
     * Gets the value of the clinicalOperations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalOperations() {
        return clinicalOperations;
    }

    /**
     * Sets the value of the clinicalOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalOperations(String value) {
        this.clinicalOperations = value;
    }

    /**
     * Gets the value of the resourcesInformationText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourcesInformationText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourcesInformationText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getResourcesInformationText() {
        if (resourcesInformationText == null) {
            resourcesInformationText = new ArrayList<Object>();
        }
        return this.resourcesInformationText;
    }

    /**
     * Gets the value of the commentText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCommentText() {
        if (commentText == null) {
            commentText = new ArrayList<String>();
        }
        return this.commentText;
    }

}
