//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 05:44:00 PM EET 
//


package oasis.names.tc.emergency.edxl.have._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.have._1_0.geo_oasis.WhereType;


/**
 * The container element for specifying the geo-coded address. 
 * 
 * <p>Java class for OrganizationGeoLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganizationGeoLocation">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0:geo-oasis}WhereType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganizationGeoLocation")
public class OrganizationGeoLocation
    extends WhereType
{


}
