//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 05:44:00 PM EET 
//


package oasis.names.tc.emergency.edxl.have._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Container element of all the elements of service coverage. This includes both the necessary staff and facilities.  Indicator of the availability of specialty service coverage.
 * 
 * <p>Java class for ServiceCoverageStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceCoverageStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Burn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CardiologyIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Cardiology" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="CardiologySubType" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CardiologyInvasive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="CardiologyNonInvasive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dialysis" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EmergencyDepartment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="HyperbaricChamber" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="InfectiousDisease" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Neonatology" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NeurologyIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Neurology" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="NeurologySubType" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NeurologyInvasive" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                             &lt;element name="NeurologyNonInvasive" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OBGYNIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="OBGYN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="OBGYNSubType" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OBGYNWithLaborDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="OBGYNWithoutLaborDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Ophthalmology" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Orthopedic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Pediatrics" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="PsychiatricIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Psychiatric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="PsychiatricSubType" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PsychiatricAdultGeneral" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="PsychiatricPediatric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SurgeryIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Surgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="SurgerySubType" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="General" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="AdultGeneralSurgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Pediatrics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Orthopedics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Neurosurgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Facial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="CardioThoracic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Hand" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Reimplantation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Spinal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Vascular" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="Anesthesia" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TransportServicesIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="TransportServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="TransportServicesSubType" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AmbulanceServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="AirTransportServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TraumaCenterServicesIndicator" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TraumaCenterServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="TraumaCenterServicesLevel" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Level1"/>
 *                         &lt;enumeration value="Level2"/>
 *                         &lt;enumeration value="Level3"/>
 *                         &lt;enumeration value="Level4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{urn:oasis:names:tc:emergency:EDXL:HAVE:1.0}CommentText" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceCoverageStatus", propOrder = {
    "burn",
    "cardiologyIndicator",
    "dialysis",
    "emergencyDepartment",
    "hyperbaricChamber",
    "infectiousDisease",
    "neonatology",
    "neurologyIndicator",
    "obgynIndicator",
    "ophthalmology",
    "orthopedic",
    "pediatrics",
    "psychiatricIndicator",
    "surgeryIndicator",
    "transportServicesIndicator",
    "traumaCenterServicesIndicator",
    "commentText"
})
public class ServiceCoverageStatus {

    @XmlElement(name = "Burn")
    protected Boolean burn;
    @XmlElement(name = "CardiologyIndicator")
    protected ServiceCoverageStatus.CardiologyIndicator cardiologyIndicator;
    @XmlElement(name = "Dialysis")
    protected Boolean dialysis;
    @XmlElement(name = "EmergencyDepartment")
    protected Boolean emergencyDepartment;
    @XmlElement(name = "HyperbaricChamber")
    protected Boolean hyperbaricChamber;
    @XmlElement(name = "InfectiousDisease")
    protected Boolean infectiousDisease;
    @XmlElement(name = "Neonatology")
    protected Boolean neonatology;
    @XmlElement(name = "NeurologyIndicator")
    protected ServiceCoverageStatus.NeurologyIndicator neurologyIndicator;
    @XmlElement(name = "OBGYNIndicator")
    protected ServiceCoverageStatus.OBGYNIndicator obgynIndicator;
    @XmlElement(name = "Ophthalmology")
    protected Boolean ophthalmology;
    @XmlElement(name = "Orthopedic")
    protected Boolean orthopedic;
    @XmlElement(name = "Pediatrics")
    protected Object pediatrics;
    @XmlElement(name = "PsychiatricIndicator")
    protected ServiceCoverageStatus.PsychiatricIndicator psychiatricIndicator;
    @XmlElement(name = "SurgeryIndicator")
    protected ServiceCoverageStatus.SurgeryIndicator surgeryIndicator;
    @XmlElement(name = "TransportServicesIndicator")
    protected ServiceCoverageStatus.TransportServicesIndicator transportServicesIndicator;
    @XmlElement(name = "TraumaCenterServicesIndicator")
    protected ServiceCoverageStatus.TraumaCenterServicesIndicator traumaCenterServicesIndicator;
    @XmlElement(name = "CommentText")
    protected List<String> commentText;

    /**
     * Gets the value of the burn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBurn() {
        return burn;
    }

    /**
     * Sets the value of the burn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBurn(Boolean value) {
        this.burn = value;
    }

    /**
     * Gets the value of the cardiologyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.CardiologyIndicator }
     *     
     */
    public ServiceCoverageStatus.CardiologyIndicator getCardiologyIndicator() {
        return cardiologyIndicator;
    }

    /**
     * Sets the value of the cardiologyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.CardiologyIndicator }
     *     
     */
    public void setCardiologyIndicator(ServiceCoverageStatus.CardiologyIndicator value) {
        this.cardiologyIndicator = value;
    }

    /**
     * Gets the value of the dialysis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDialysis() {
        return dialysis;
    }

    /**
     * Sets the value of the dialysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDialysis(Boolean value) {
        this.dialysis = value;
    }

    /**
     * Gets the value of the emergencyDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmergencyDepartment() {
        return emergencyDepartment;
    }

    /**
     * Sets the value of the emergencyDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmergencyDepartment(Boolean value) {
        this.emergencyDepartment = value;
    }

    /**
     * Gets the value of the hyperbaricChamber property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHyperbaricChamber() {
        return hyperbaricChamber;
    }

    /**
     * Sets the value of the hyperbaricChamber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHyperbaricChamber(Boolean value) {
        this.hyperbaricChamber = value;
    }

    /**
     * Gets the value of the infectiousDisease property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInfectiousDisease() {
        return infectiousDisease;
    }

    /**
     * Sets the value of the infectiousDisease property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInfectiousDisease(Boolean value) {
        this.infectiousDisease = value;
    }

    /**
     * Gets the value of the neonatology property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNeonatology() {
        return neonatology;
    }

    /**
     * Sets the value of the neonatology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeonatology(Boolean value) {
        this.neonatology = value;
    }

    /**
     * Gets the value of the neurologyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.NeurologyIndicator }
     *     
     */
    public ServiceCoverageStatus.NeurologyIndicator getNeurologyIndicator() {
        return neurologyIndicator;
    }

    /**
     * Sets the value of the neurologyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.NeurologyIndicator }
     *     
     */
    public void setNeurologyIndicator(ServiceCoverageStatus.NeurologyIndicator value) {
        this.neurologyIndicator = value;
    }

    /**
     * Gets the value of the obgynIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.OBGYNIndicator }
     *     
     */
    public ServiceCoverageStatus.OBGYNIndicator getOBGYNIndicator() {
        return obgynIndicator;
    }

    /**
     * Sets the value of the obgynIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.OBGYNIndicator }
     *     
     */
    public void setOBGYNIndicator(ServiceCoverageStatus.OBGYNIndicator value) {
        this.obgynIndicator = value;
    }

    /**
     * Gets the value of the ophthalmology property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOphthalmology() {
        return ophthalmology;
    }

    /**
     * Sets the value of the ophthalmology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOphthalmology(Boolean value) {
        this.ophthalmology = value;
    }

    /**
     * Gets the value of the orthopedic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOrthopedic() {
        return orthopedic;
    }

    /**
     * Sets the value of the orthopedic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrthopedic(Boolean value) {
        this.orthopedic = value;
    }

    /**
     * Gets the value of the pediatrics property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPediatrics() {
        return pediatrics;
    }

    /**
     * Sets the value of the pediatrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPediatrics(Object value) {
        this.pediatrics = value;
    }

    /**
     * Gets the value of the psychiatricIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.PsychiatricIndicator }
     *     
     */
    public ServiceCoverageStatus.PsychiatricIndicator getPsychiatricIndicator() {
        return psychiatricIndicator;
    }

    /**
     * Sets the value of the psychiatricIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.PsychiatricIndicator }
     *     
     */
    public void setPsychiatricIndicator(ServiceCoverageStatus.PsychiatricIndicator value) {
        this.psychiatricIndicator = value;
    }

    /**
     * Gets the value of the surgeryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.SurgeryIndicator }
     *     
     */
    public ServiceCoverageStatus.SurgeryIndicator getSurgeryIndicator() {
        return surgeryIndicator;
    }

    /**
     * Sets the value of the surgeryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.SurgeryIndicator }
     *     
     */
    public void setSurgeryIndicator(ServiceCoverageStatus.SurgeryIndicator value) {
        this.surgeryIndicator = value;
    }

    /**
     * Gets the value of the transportServicesIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.TransportServicesIndicator }
     *     
     */
    public ServiceCoverageStatus.TransportServicesIndicator getTransportServicesIndicator() {
        return transportServicesIndicator;
    }

    /**
     * Sets the value of the transportServicesIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.TransportServicesIndicator }
     *     
     */
    public void setTransportServicesIndicator(ServiceCoverageStatus.TransportServicesIndicator value) {
        this.transportServicesIndicator = value;
    }

    /**
     * Gets the value of the traumaCenterServicesIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCoverageStatus.TraumaCenterServicesIndicator }
     *     
     */
    public ServiceCoverageStatus.TraumaCenterServicesIndicator getTraumaCenterServicesIndicator() {
        return traumaCenterServicesIndicator;
    }

    /**
     * Sets the value of the traumaCenterServicesIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCoverageStatus.TraumaCenterServicesIndicator }
     *     
     */
    public void setTraumaCenterServicesIndicator(ServiceCoverageStatus.TraumaCenterServicesIndicator value) {
        this.traumaCenterServicesIndicator = value;
    }

    /**
     * Gets the value of the commentText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCommentText() {
        if (commentText == null) {
            commentText = new ArrayList<String>();
        }
        return this.commentText;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Cardiology" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="CardiologySubType" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CardiologyInvasive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="CardiologyNonInvasive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cardiology",
        "cardiologySubType"
    })
    public static class CardiologyIndicator {

        @XmlElement(name = "Cardiology")
        protected Boolean cardiology;
        @XmlElement(name = "CardiologySubType")
        protected ServiceCoverageStatus.CardiologyIndicator.CardiologySubType cardiologySubType;

        /**
         * Gets the value of the cardiology property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isCardiology() {
            return cardiology;
        }

        /**
         * Sets the value of the cardiology property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCardiology(Boolean value) {
            this.cardiology = value;
        }

        /**
         * Gets the value of the cardiologySubType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceCoverageStatus.CardiologyIndicator.CardiologySubType }
         *     
         */
        public ServiceCoverageStatus.CardiologyIndicator.CardiologySubType getCardiologySubType() {
            return cardiologySubType;
        }

        /**
         * Sets the value of the cardiologySubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceCoverageStatus.CardiologyIndicator.CardiologySubType }
         *     
         */
        public void setCardiologySubType(ServiceCoverageStatus.CardiologyIndicator.CardiologySubType value) {
            this.cardiologySubType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CardiologyInvasive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="CardiologyNonInvasive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cardiologyInvasive",
            "cardiologyNonInvasive"
        })
        public static class CardiologySubType {

            @XmlElement(name = "CardiologyInvasive")
            protected Boolean cardiologyInvasive;
            @XmlElement(name = "CardiologyNonInvasive")
            protected Boolean cardiologyNonInvasive;

            /**
             * Gets the value of the cardiologyInvasive property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isCardiologyInvasive() {
                return cardiologyInvasive;
            }

            /**
             * Sets the value of the cardiologyInvasive property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setCardiologyInvasive(Boolean value) {
                this.cardiologyInvasive = value;
            }

            /**
             * Gets the value of the cardiologyNonInvasive property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isCardiologyNonInvasive() {
                return cardiologyNonInvasive;
            }

            /**
             * Sets the value of the cardiologyNonInvasive property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setCardiologyNonInvasive(Boolean value) {
                this.cardiologyNonInvasive = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Neurology" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="NeurologySubType" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NeurologyInvasive" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                   &lt;element name="NeurologyNonInvasive" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "neurology",
        "neurologySubType"
    })
    public static class NeurologyIndicator {

        @XmlElement(name = "Neurology")
        protected Boolean neurology;
        @XmlElement(name = "NeurologySubType")
        protected ServiceCoverageStatus.NeurologyIndicator.NeurologySubType neurologySubType;

        /**
         * Gets the value of the neurology property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNeurology() {
            return neurology;
        }

        /**
         * Sets the value of the neurology property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNeurology(Boolean value) {
            this.neurology = value;
        }

        /**
         * Gets the value of the neurologySubType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceCoverageStatus.NeurologyIndicator.NeurologySubType }
         *     
         */
        public ServiceCoverageStatus.NeurologyIndicator.NeurologySubType getNeurologySubType() {
            return neurologySubType;
        }

        /**
         * Sets the value of the neurologySubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceCoverageStatus.NeurologyIndicator.NeurologySubType }
         *     
         */
        public void setNeurologySubType(ServiceCoverageStatus.NeurologyIndicator.NeurologySubType value) {
            this.neurologySubType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NeurologyInvasive" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *         &lt;element name="NeurologyNonInvasive" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "neurologyInvasive",
            "neurologyNonInvasive"
        })
        public static class NeurologySubType {

            @XmlElement(name = "NeurologyInvasive")
            protected Object neurologyInvasive;
            @XmlElement(name = "NeurologyNonInvasive")
            protected Object neurologyNonInvasive;

            /**
             * Gets the value of the neurologyInvasive property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getNeurologyInvasive() {
                return neurologyInvasive;
            }

            /**
             * Sets the value of the neurologyInvasive property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setNeurologyInvasive(Object value) {
                this.neurologyInvasive = value;
            }

            /**
             * Gets the value of the neurologyNonInvasive property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getNeurologyNonInvasive() {
                return neurologyNonInvasive;
            }

            /**
             * Sets the value of the neurologyNonInvasive property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setNeurologyNonInvasive(Object value) {
                this.neurologyNonInvasive = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="OBGYN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="OBGYNSubType" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OBGYNWithLaborDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="OBGYNWithoutLaborDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "obgyn",
        "obgynSubType"
    })
    public static class OBGYNIndicator {

        @XmlElement(name = "OBGYN")
        protected Boolean obgyn;
        @XmlElement(name = "OBGYNSubType")
        protected ServiceCoverageStatus.OBGYNIndicator.OBGYNSubType obgynSubType;

        /**
         * Gets the value of the obgyn property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isOBGYN() {
            return obgyn;
        }

        /**
         * Sets the value of the obgyn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOBGYN(Boolean value) {
            this.obgyn = value;
        }

        /**
         * Gets the value of the obgynSubType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceCoverageStatus.OBGYNIndicator.OBGYNSubType }
         *     
         */
        public ServiceCoverageStatus.OBGYNIndicator.OBGYNSubType getOBGYNSubType() {
            return obgynSubType;
        }

        /**
         * Sets the value of the obgynSubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceCoverageStatus.OBGYNIndicator.OBGYNSubType }
         *     
         */
        public void setOBGYNSubType(ServiceCoverageStatus.OBGYNIndicator.OBGYNSubType value) {
            this.obgynSubType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OBGYNWithLaborDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="OBGYNWithoutLaborDelivery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "obgynWithLaborDelivery",
            "obgynWithoutLaborDelivery"
        })
        public static class OBGYNSubType {

            @XmlElement(name = "OBGYNWithLaborDelivery")
            protected Boolean obgynWithLaborDelivery;
            @XmlElement(name = "OBGYNWithoutLaborDelivery")
            protected Boolean obgynWithoutLaborDelivery;

            /**
             * Gets the value of the obgynWithLaborDelivery property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOBGYNWithLaborDelivery() {
                return obgynWithLaborDelivery;
            }

            /**
             * Sets the value of the obgynWithLaborDelivery property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOBGYNWithLaborDelivery(Boolean value) {
                this.obgynWithLaborDelivery = value;
            }

            /**
             * Gets the value of the obgynWithoutLaborDelivery property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOBGYNWithoutLaborDelivery() {
                return obgynWithoutLaborDelivery;
            }

            /**
             * Sets the value of the obgynWithoutLaborDelivery property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOBGYNWithoutLaborDelivery(Boolean value) {
                this.obgynWithoutLaborDelivery = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Psychiatric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="PsychiatricSubType" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PsychiatricAdultGeneral" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="PsychiatricPediatric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "psychiatric",
        "psychiatricSubType"
    })
    public static class PsychiatricIndicator {

        @XmlElement(name = "Psychiatric")
        protected Boolean psychiatric;
        @XmlElement(name = "PsychiatricSubType")
        protected ServiceCoverageStatus.PsychiatricIndicator.PsychiatricSubType psychiatricSubType;

        /**
         * Gets the value of the psychiatric property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isPsychiatric() {
            return psychiatric;
        }

        /**
         * Sets the value of the psychiatric property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPsychiatric(Boolean value) {
            this.psychiatric = value;
        }

        /**
         * Gets the value of the psychiatricSubType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceCoverageStatus.PsychiatricIndicator.PsychiatricSubType }
         *     
         */
        public ServiceCoverageStatus.PsychiatricIndicator.PsychiatricSubType getPsychiatricSubType() {
            return psychiatricSubType;
        }

        /**
         * Sets the value of the psychiatricSubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceCoverageStatus.PsychiatricIndicator.PsychiatricSubType }
         *     
         */
        public void setPsychiatricSubType(ServiceCoverageStatus.PsychiatricIndicator.PsychiatricSubType value) {
            this.psychiatricSubType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PsychiatricAdultGeneral" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="PsychiatricPediatric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "psychiatricAdultGeneral",
            "psychiatricPediatric"
        })
        public static class PsychiatricSubType {

            @XmlElement(name = "PsychiatricAdultGeneral")
            protected Boolean psychiatricAdultGeneral;
            @XmlElement(name = "PsychiatricPediatric")
            protected Boolean psychiatricPediatric;

            /**
             * Gets the value of the psychiatricAdultGeneral property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPsychiatricAdultGeneral() {
                return psychiatricAdultGeneral;
            }

            /**
             * Sets the value of the psychiatricAdultGeneral property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPsychiatricAdultGeneral(Boolean value) {
                this.psychiatricAdultGeneral = value;
            }

            /**
             * Gets the value of the psychiatricPediatric property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPsychiatricPediatric() {
                return psychiatricPediatric;
            }

            /**
             * Sets the value of the psychiatricPediatric property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPsychiatricPediatric(Boolean value) {
                this.psychiatricPediatric = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Surgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="SurgerySubType" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="General" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="AdultGeneralSurgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Pediatrics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Orthopedics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Neurosurgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Facial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="CardioThoracic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Hand" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Reimplantation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Spinal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Vascular" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="Anesthesia" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "surgery",
        "surgerySubType"
    })
    public static class SurgeryIndicator {

        @XmlElement(name = "Surgery")
        protected Boolean surgery;
        @XmlElement(name = "SurgerySubType")
        protected ServiceCoverageStatus.SurgeryIndicator.SurgerySubType surgerySubType;

        /**
         * Gets the value of the surgery property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSurgery() {
            return surgery;
        }

        /**
         * Sets the value of the surgery property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSurgery(Boolean value) {
            this.surgery = value;
        }

        /**
         * Gets the value of the surgerySubType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceCoverageStatus.SurgeryIndicator.SurgerySubType }
         *     
         */
        public ServiceCoverageStatus.SurgeryIndicator.SurgerySubType getSurgerySubType() {
            return surgerySubType;
        }

        /**
         * Sets the value of the surgerySubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceCoverageStatus.SurgeryIndicator.SurgerySubType }
         *     
         */
        public void setSurgerySubType(ServiceCoverageStatus.SurgeryIndicator.SurgerySubType value) {
            this.surgerySubType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="General" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="AdultGeneralSurgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Pediatrics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Orthopedics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Neurosurgery" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Facial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="CardioThoracic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Hand" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Reimplantation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Spinal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Vascular" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="Anesthesia" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "general",
            "adultGeneralSurgery",
            "pediatrics",
            "orthopedics",
            "neurosurgery",
            "facial",
            "cardioThoracic",
            "hand",
            "reimplantation",
            "spinal",
            "vascular",
            "anesthesia"
        })
        public static class SurgerySubType {

            @XmlElement(name = "General")
            protected Boolean general;
            @XmlElement(name = "AdultGeneralSurgery")
            protected Boolean adultGeneralSurgery;
            @XmlElement(name = "Pediatrics")
            protected Boolean pediatrics;
            @XmlElement(name = "Orthopedics")
            protected Boolean orthopedics;
            @XmlElement(name = "Neurosurgery")
            protected Boolean neurosurgery;
            @XmlElement(name = "Facial")
            protected Boolean facial;
            @XmlElement(name = "CardioThoracic")
            protected Boolean cardioThoracic;
            @XmlElement(name = "Hand")
            protected Boolean hand;
            @XmlElement(name = "Reimplantation")
            protected Boolean reimplantation;
            @XmlElement(name = "Spinal")
            protected Boolean spinal;
            @XmlElement(name = "Vascular")
            protected Boolean vascular;
            @XmlElement(name = "Anesthesia")
            protected Boolean anesthesia;

            /**
             * Gets the value of the general property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGeneral() {
                return general;
            }

            /**
             * Sets the value of the general property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGeneral(Boolean value) {
                this.general = value;
            }

            /**
             * Gets the value of the adultGeneralSurgery property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAdultGeneralSurgery() {
                return adultGeneralSurgery;
            }

            /**
             * Sets the value of the adultGeneralSurgery property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAdultGeneralSurgery(Boolean value) {
                this.adultGeneralSurgery = value;
            }

            /**
             * Gets the value of the pediatrics property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isPediatrics() {
                return pediatrics;
            }

            /**
             * Sets the value of the pediatrics property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setPediatrics(Boolean value) {
                this.pediatrics = value;
            }

            /**
             * Gets the value of the orthopedics property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOrthopedics() {
                return orthopedics;
            }

            /**
             * Sets the value of the orthopedics property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOrthopedics(Boolean value) {
                this.orthopedics = value;
            }

            /**
             * Gets the value of the neurosurgery property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isNeurosurgery() {
                return neurosurgery;
            }

            /**
             * Sets the value of the neurosurgery property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNeurosurgery(Boolean value) {
                this.neurosurgery = value;
            }

            /**
             * Gets the value of the facial property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isFacial() {
                return facial;
            }

            /**
             * Sets the value of the facial property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setFacial(Boolean value) {
                this.facial = value;
            }

            /**
             * Gets the value of the cardioThoracic property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isCardioThoracic() {
                return cardioThoracic;
            }

            /**
             * Sets the value of the cardioThoracic property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setCardioThoracic(Boolean value) {
                this.cardioThoracic = value;
            }

            /**
             * Gets the value of the hand property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isHand() {
                return hand;
            }

            /**
             * Sets the value of the hand property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setHand(Boolean value) {
                this.hand = value;
            }

            /**
             * Gets the value of the reimplantation property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isReimplantation() {
                return reimplantation;
            }

            /**
             * Sets the value of the reimplantation property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setReimplantation(Boolean value) {
                this.reimplantation = value;
            }

            /**
             * Gets the value of the spinal property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isSpinal() {
                return spinal;
            }

            /**
             * Sets the value of the spinal property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setSpinal(Boolean value) {
                this.spinal = value;
            }

            /**
             * Gets the value of the vascular property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isVascular() {
                return vascular;
            }

            /**
             * Sets the value of the vascular property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setVascular(Boolean value) {
                this.vascular = value;
            }

            /**
             * Gets the value of the anesthesia property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAnesthesia() {
                return anesthesia;
            }

            /**
             * Sets the value of the anesthesia property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAnesthesia(Boolean value) {
                this.anesthesia = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="TransportServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="TransportServicesSubType" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AmbulanceServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="AirTransportServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transportServices",
        "transportServicesSubType"
    })
    public static class TransportServicesIndicator {

        @XmlElement(name = "TransportServices")
        protected Boolean transportServices;
        @XmlElement(name = "TransportServicesSubType")
        protected ServiceCoverageStatus.TransportServicesIndicator.TransportServicesSubType transportServicesSubType;

        /**
         * Gets the value of the transportServices property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isTransportServices() {
            return transportServices;
        }

        /**
         * Sets the value of the transportServices property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setTransportServices(Boolean value) {
            this.transportServices = value;
        }

        /**
         * Gets the value of the transportServicesSubType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceCoverageStatus.TransportServicesIndicator.TransportServicesSubType }
         *     
         */
        public ServiceCoverageStatus.TransportServicesIndicator.TransportServicesSubType getTransportServicesSubType() {
            return transportServicesSubType;
        }

        /**
         * Sets the value of the transportServicesSubType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceCoverageStatus.TransportServicesIndicator.TransportServicesSubType }
         *     
         */
        public void setTransportServicesSubType(ServiceCoverageStatus.TransportServicesIndicator.TransportServicesSubType value) {
            this.transportServicesSubType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AmbulanceServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="AirTransportServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ambulanceServices",
            "airTransportServices"
        })
        public static class TransportServicesSubType {

            @XmlElement(name = "AmbulanceServices")
            protected Boolean ambulanceServices;
            @XmlElement(name = "AirTransportServices")
            protected Boolean airTransportServices;

            /**
             * Gets the value of the ambulanceServices property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAmbulanceServices() {
                return ambulanceServices;
            }

            /**
             * Sets the value of the ambulanceServices property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAmbulanceServices(Boolean value) {
                this.ambulanceServices = value;
            }

            /**
             * Gets the value of the airTransportServices property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAirTransportServices() {
                return airTransportServices;
            }

            /**
             * Sets the value of the airTransportServices property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAirTransportServices(Boolean value) {
                this.airTransportServices = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TraumaCenterServices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="TraumaCenterServicesLevel" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Level1"/>
     *               &lt;enumeration value="Level2"/>
     *               &lt;enumeration value="Level3"/>
     *               &lt;enumeration value="Level4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "traumaCenterServices",
        "traumaCenterServicesLevel"
    })
    public static class TraumaCenterServicesIndicator {

        @XmlElement(name = "TraumaCenterServices")
        protected Boolean traumaCenterServices;
        @XmlElement(name = "TraumaCenterServicesLevel")
        protected String traumaCenterServicesLevel;

        /**
         * Gets the value of the traumaCenterServices property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isTraumaCenterServices() {
            return traumaCenterServices;
        }

        /**
         * Sets the value of the traumaCenterServices property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setTraumaCenterServices(Boolean value) {
            this.traumaCenterServices = value;
        }

        /**
         * Gets the value of the traumaCenterServicesLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTraumaCenterServicesLevel() {
            return traumaCenterServicesLevel;
        }

        /**
         * Sets the value of the traumaCenterServicesLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTraumaCenterServicesLevel(String value) {
            this.traumaCenterServicesLevel = value;
        }

    }

}
