package eu.impress.logevo.util;

public enum Symptom {
	ATTITUDE("1"), COMPLETEOBSTRUCTIONOFTHEAIRWAYS("2"),PARTIALOBSTRUCTIONOFTHEAIRWAYS("3"),
	STRIDOR("4"),STRETOR("5"),REDUCEDBREATHINGSOUNDS("6"),RESPIRATORYRATE("7"),
	CYANOSIS("8"),HEMOPTYSIS("9"),HEARTRATE("10"),SYSTOLICBLOODPRESSURE("11"),
	GCS("12"),ACTIVEMOVEMENT("13"),SENSIBILITY("14"),PAINTENDERNESS("15"),WOUNDS("16"),
	EXITWOUNDS("17"),PENETRATINGWOUNDS("18"),HEMATOMA("19"),FRACTURE("20"),BURN("21"),
	EXTENSIVELACERATION("22"),TRAUMATICAMPUTATION("23"),DISLOCATEDJOINT("24");
	
	private String val;
	public String getVal() {
		return val;
	}
	private Symptom(String val) {
		this.val = val;		
	}	
}
