//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:02:17 PM EEST 
//


package oasis.names.tc.emergency.edxl.ct._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.emergency.edxl.gsf._1.EDXLGeoLocationType;


/**
 * A Container for describing both Geo-Political and Geographic Locations
 * 
 * <p>Java class for EDXLLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EDXLLocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="EDXLGeoLocation" type="{urn:oasis:names:tc:emergency:edxl:gsf:1.0}EDXLGeoLocationType"/>
 *         &lt;element name="EDXLGeoPoliticalLocation" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}EDXLGeoPoliticalLocationType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EDXLLocationType", propOrder = {
    "edxlGeoLocation",
    "edxlGeoPoliticalLocation"
})
public class EDXLLocationType {

    @XmlElement(name = "EDXLGeoLocation")
    protected EDXLGeoLocationType edxlGeoLocation;
    @XmlElement(name = "EDXLGeoPoliticalLocation")
    protected EDXLGeoPoliticalLocationType edxlGeoPoliticalLocation;

    /**
     * Gets the value of the edxlGeoLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EDXLGeoLocationType }
     *     
     */
    public EDXLGeoLocationType getEDXLGeoLocation() {
        return edxlGeoLocation;
    }

    /**
     * Sets the value of the edxlGeoLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXLGeoLocationType }
     *     
     */
    public void setEDXLGeoLocation(EDXLGeoLocationType value) {
        this.edxlGeoLocation = value;
    }

    /**
     * Gets the value of the edxlGeoPoliticalLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EDXLGeoPoliticalLocationType }
     *     
     */
    public EDXLGeoPoliticalLocationType getEDXLGeoPoliticalLocation() {
        return edxlGeoPoliticalLocation;
    }

    /**
     * Sets the value of the edxlGeoPoliticalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDXLGeoPoliticalLocationType }
     *     
     */
    public void setEDXLGeoPoliticalLocation(EDXLGeoPoliticalLocationType value) {
        this.edxlGeoPoliticalLocation = value;
    }

}
