//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.ct._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmergencyResponseIssuesDefaultValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EmergencyResponseIssuesDefaultValues">
 *   &lt;restriction base="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueType">
 *     &lt;enumeration value="ESF11AgricultureAndNaturalResources"/>
 *     &lt;enumeration value="ESF2Communications"/>
 *     &lt;enumeration value="ESF5EmergencyManagement"/>
 *     &lt;enumeration value="ESF12Energy"/>
 *     &lt;enumeration value="ESF15ExternalAffairs"/>
 *     &lt;enumeration value="ESF4Firefighting"/>
 *     &lt;enumeration value="ESF7LogisticsManagementResourceSupport"/>
 *     &lt;enumeration value="ESF14LongTermCommunityRecoveryAndMitigation"/>
 *     &lt;enumeration value="ESF6MassCareHousingAndHumanServices"/>
 *     &lt;enumeration value="ESF10OilAndHazardousMaterialsResponse"/>
 *     &lt;enumeration value="ESF8PublicHealthAndMedicalServices"/>
 *     &lt;enumeration value="ESF13PublicSafetyAndSecurity"/>
 *     &lt;enumeration value="ESF3PublicWorksAndEngineering"/>
 *     &lt;enumeration value="ESF9SearchAndRescue"/>
 *     &lt;enumeration value="ESF1Transportation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EmergencyResponseIssuesDefaultValues")
@XmlEnum
public enum EmergencyResponseIssuesDefaultValues {

    @XmlEnumValue("ESF11AgricultureAndNaturalResources")
    ESF_11_AGRICULTURE_AND_NATURAL_RESOURCES("ESF11AgricultureAndNaturalResources"),
    @XmlEnumValue("ESF2Communications")
    ESF_2_COMMUNICATIONS("ESF2Communications"),
    @XmlEnumValue("ESF5EmergencyManagement")
    ESF_5_EMERGENCY_MANAGEMENT("ESF5EmergencyManagement"),
    @XmlEnumValue("ESF12Energy")
    ESF_12_ENERGY("ESF12Energy"),
    @XmlEnumValue("ESF15ExternalAffairs")
    ESF_15_EXTERNAL_AFFAIRS("ESF15ExternalAffairs"),
    @XmlEnumValue("ESF4Firefighting")
    ESF_4_FIREFIGHTING("ESF4Firefighting"),
    @XmlEnumValue("ESF7LogisticsManagementResourceSupport")
    ESF_7_LOGISTICS_MANAGEMENT_RESOURCE_SUPPORT("ESF7LogisticsManagementResourceSupport"),
    @XmlEnumValue("ESF14LongTermCommunityRecoveryAndMitigation")
    ESF_14_LONG_TERM_COMMUNITY_RECOVERY_AND_MITIGATION("ESF14LongTermCommunityRecoveryAndMitigation"),
    @XmlEnumValue("ESF6MassCareHousingAndHumanServices")
    ESF_6_MASS_CARE_HOUSING_AND_HUMAN_SERVICES("ESF6MassCareHousingAndHumanServices"),
    @XmlEnumValue("ESF10OilAndHazardousMaterialsResponse")
    ESF_10_OIL_AND_HAZARDOUS_MATERIALS_RESPONSE("ESF10OilAndHazardousMaterialsResponse"),
    @XmlEnumValue("ESF8PublicHealthAndMedicalServices")
    ESF_8_PUBLIC_HEALTH_AND_MEDICAL_SERVICES("ESF8PublicHealthAndMedicalServices"),
    @XmlEnumValue("ESF13PublicSafetyAndSecurity")
    ESF_13_PUBLIC_SAFETY_AND_SECURITY("ESF13PublicSafetyAndSecurity"),
    @XmlEnumValue("ESF3PublicWorksAndEngineering")
    ESF_3_PUBLIC_WORKS_AND_ENGINEERING("ESF3PublicWorksAndEngineering"),
    @XmlEnumValue("ESF9SearchAndRescue")
    ESF_9_SEARCH_AND_RESCUE("ESF9SearchAndRescue"),
    @XmlEnumValue("ESF1Transportation")
    ESF_1_TRANSPORTATION("ESF1Transportation");
    private final String value;

    EmergencyResponseIssuesDefaultValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmergencyResponseIssuesDefaultValues fromValue(String v) {
        for (EmergencyResponseIssuesDefaultValues c: EmergencyResponseIssuesDefaultValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
