//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.ct._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncidentTypeDefaultValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncidentTypeDefaultValues">
 *   &lt;restriction base="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueType">
 *     &lt;enumeration value="Geophysical"/>
 *     &lt;enumeration value="Meteorological"/>
 *     &lt;enumeration value="GeneralEmergency"/>
 *     &lt;enumeration value="Safety"/>
 *     &lt;enumeration value="Security"/>
 *     &lt;enumeration value="RescueAndRecovery"/>
 *     &lt;enumeration value="Rescue"/>
 *     &lt;enumeration value="FireSupressionAndRescue"/>
 *     &lt;enumeration value="Fire"/>
 *     &lt;enumeration value="MedicalAndPublicHealth"/>
 *     &lt;enumeration value="Health"/>
 *     &lt;enumeration value="PollutionAndEnvironmentalHazards"/>
 *     &lt;enumeration value="PublicAndPrivateTransportation"/>
 *     &lt;enumeration value="Transport"/>
 *     &lt;enumeration value="UtilityTelecommunicationOtherNonTransportInfrastructure"/>
 *     &lt;enumeration value="CBRNE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncidentTypeDefaultValues")
@XmlEnum
public enum IncidentTypeDefaultValues {

    @XmlEnumValue("Geophysical")
    GEOPHYSICAL("Geophysical"),
    @XmlEnumValue("Meteorological")
    METEOROLOGICAL("Meteorological"),
    @XmlEnumValue("GeneralEmergency")
    GENERAL_EMERGENCY("GeneralEmergency"),
    @XmlEnumValue("Safety")
    SAFETY("Safety"),
    @XmlEnumValue("Security")
    SECURITY("Security"),
    @XmlEnumValue("RescueAndRecovery")
    RESCUE_AND_RECOVERY("RescueAndRecovery"),
    @XmlEnumValue("Rescue")
    RESCUE("Rescue"),
    @XmlEnumValue("FireSupressionAndRescue")
    FIRE_SUPRESSION_AND_RESCUE("FireSupressionAndRescue"),
    @XmlEnumValue("Fire")
    FIRE("Fire"),
    @XmlEnumValue("MedicalAndPublicHealth")
    MEDICAL_AND_PUBLIC_HEALTH("MedicalAndPublicHealth"),
    @XmlEnumValue("Health")
    HEALTH("Health"),
    @XmlEnumValue("PollutionAndEnvironmentalHazards")
    POLLUTION_AND_ENVIRONMENTAL_HAZARDS("PollutionAndEnvironmentalHazards"),
    @XmlEnumValue("PublicAndPrivateTransportation")
    PUBLIC_AND_PRIVATE_TRANSPORTATION("PublicAndPrivateTransportation"),
    @XmlEnumValue("Transport")
    TRANSPORT("Transport"),
    @XmlEnumValue("UtilityTelecommunicationOtherNonTransportInfrastructure")
    UTILITY_TELECOMMUNICATION_OTHER_NON_TRANSPORT_INFRASTRUCTURE("UtilityTelecommunicationOtherNonTransportInfrastructure"),
    CBRNE("CBRNE");
    private final String value;

    IncidentTypeDefaultValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncidentTypeDefaultValues fromValue(String v) {
        for (IncidentTypeDefaultValues c: IncidentTypeDefaultValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
