//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 12:31:13 PM EET 
//


package oasis.names.tc.emergency.edxl.ct._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfrastructureAffectedDefaultValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InfrastructureAffectedDefaultValues">
 *   &lt;restriction base="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueType">
 *     &lt;enumeration value="MassTransit"/>
 *     &lt;enumeration value="RoadsAndHighways"/>
 *     &lt;enumeration value="Railway"/>
 *     &lt;enumeration value="BridgesAndTunnels"/>
 *     &lt;enumeration value="Seaports"/>
 *     &lt;enumeration value="Waterways"/>
 *     &lt;enumeration value="Airports"/>
 *     &lt;enumeration value="Broadcast"/>
 *     &lt;enumeration value="Power"/>
 *     &lt;enumeration value="Water"/>
 *     &lt;enumeration value="Bridges"/>
 *     &lt;enumeration value="GasLines"/>
 *     &lt;enumeration value="Nuclear"/>
 *     &lt;enumeration value="ConduitsAndRaceways"/>
 *     &lt;enumeration value="CablingAndPatchPanels"/>
 *     &lt;enumeration value="PowerAndEnergy"/>
 *     &lt;enumeration value="AirConditioning"/>
 *     &lt;enumeration value="DrinkingWater"/>
 *     &lt;enumeration value="Sewage"/>
 *     &lt;enumeration value="Irrigation"/>
 *     &lt;enumeration value="WasteOrHazardousWaste"/>
 *     &lt;enumeration value="FloodControl"/>
 *     &lt;enumeration value="EarthMonitoringAndMeasurementNetworks"/>
 *     &lt;enumeration value="Postal"/>
 *     &lt;enumeration value="TelecommunicationsPhone"/>
 *     &lt;enumeration value="TelecommunicationsMobile"/>
 *     &lt;enumeration value="InternetBackbone"/>
 *     &lt;enumeration value="PrivateNetwork"/>
 *     &lt;enumeration value="Satellite"/>
 *     &lt;enumeration value="ElectronicCommunicationsNetworks"/>
 *     &lt;enumeration value="PersonalComputingServersAndDevices"/>
 *     &lt;enumeration value="TrainedPersonnel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InfrastructureAffectedDefaultValues")
@XmlEnum
public enum InfrastructureAffectedDefaultValues {

    @XmlEnumValue("MassTransit")
    MASS_TRANSIT("MassTransit"),
    @XmlEnumValue("RoadsAndHighways")
    ROADS_AND_HIGHWAYS("RoadsAndHighways"),
    @XmlEnumValue("Railway")
    RAILWAY("Railway"),
    @XmlEnumValue("BridgesAndTunnels")
    BRIDGES_AND_TUNNELS("BridgesAndTunnels"),
    @XmlEnumValue("Seaports")
    SEAPORTS("Seaports"),
    @XmlEnumValue("Waterways")
    WATERWAYS("Waterways"),
    @XmlEnumValue("Airports")
    AIRPORTS("Airports"),
    @XmlEnumValue("Broadcast")
    BROADCAST("Broadcast"),
    @XmlEnumValue("Power")
    POWER("Power"),
    @XmlEnumValue("Water")
    WATER("Water"),
    @XmlEnumValue("Bridges")
    BRIDGES("Bridges"),
    @XmlEnumValue("GasLines")
    GAS_LINES("GasLines"),
    @XmlEnumValue("Nuclear")
    NUCLEAR("Nuclear"),
    @XmlEnumValue("ConduitsAndRaceways")
    CONDUITS_AND_RACEWAYS("ConduitsAndRaceways"),
    @XmlEnumValue("CablingAndPatchPanels")
    CABLING_AND_PATCH_PANELS("CablingAndPatchPanels"),
    @XmlEnumValue("PowerAndEnergy")
    POWER_AND_ENERGY("PowerAndEnergy"),
    @XmlEnumValue("AirConditioning")
    AIR_CONDITIONING("AirConditioning"),
    @XmlEnumValue("DrinkingWater")
    DRINKING_WATER("DrinkingWater"),
    @XmlEnumValue("Sewage")
    SEWAGE("Sewage"),
    @XmlEnumValue("Irrigation")
    IRRIGATION("Irrigation"),
    @XmlEnumValue("WasteOrHazardousWaste")
    WASTE_OR_HAZARDOUS_WASTE("WasteOrHazardousWaste"),
    @XmlEnumValue("FloodControl")
    FLOOD_CONTROL("FloodControl"),
    @XmlEnumValue("EarthMonitoringAndMeasurementNetworks")
    EARTH_MONITORING_AND_MEASUREMENT_NETWORKS("EarthMonitoringAndMeasurementNetworks"),
    @XmlEnumValue("Postal")
    POSTAL("Postal"),
    @XmlEnumValue("TelecommunicationsPhone")
    TELECOMMUNICATIONS_PHONE("TelecommunicationsPhone"),
    @XmlEnumValue("TelecommunicationsMobile")
    TELECOMMUNICATIONS_MOBILE("TelecommunicationsMobile"),
    @XmlEnumValue("InternetBackbone")
    INTERNET_BACKBONE("InternetBackbone"),
    @XmlEnumValue("PrivateNetwork")
    PRIVATE_NETWORK("PrivateNetwork"),
    @XmlEnumValue("Satellite")
    SATELLITE("Satellite"),
    @XmlEnumValue("ElectronicCommunicationsNetworks")
    ELECTRONIC_COMMUNICATIONS_NETWORKS("ElectronicCommunicationsNetworks"),
    @XmlEnumValue("PersonalComputingServersAndDevices")
    PERSONAL_COMPUTING_SERVERS_AND_DEVICES("PersonalComputingServersAndDevices"),
    @XmlEnumValue("TrainedPersonnel")
    TRAINED_PERSONNEL("TrainedPersonnel");
    private final String value;

    InfrastructureAffectedDefaultValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InfrastructureAffectedDefaultValues fromValue(String v) {
        for (InfrastructureAffectedDefaultValues c: InfrastructureAffectedDefaultValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
