//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.01 at 06:02:17 PM EEST 
//


package oasis.names.tc.emergency.edxl.ct._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueKeyStringPairType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueKeyStringPairType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValueKeyURI" type="{urn:oasis:names:tc:emergency:edxl:ct:1.0}ValueKeyType"/>
 *         &lt;element name="PairValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueKeyStringPairType", propOrder = {
    "valueKeyURI",
    "pairValue"
})
public class ValueKeyStringPairType {

    @XmlElement(name = "ValueKeyURI", required = true)
    protected ValueKeyType valueKeyURI;
    @XmlElement(name = "PairValue", required = true)
    protected String pairValue;

    /**
     * Gets the value of the valueKeyURI property.
     * 
     * @return
     *     possible object is
     *     {@link ValueKeyType }
     *     
     */
    public ValueKeyType getValueKeyURI() {
        return valueKeyURI;
    }

    /**
     * Sets the value of the valueKeyURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueKeyType }
     *     
     */
    public void setValueKeyURI(ValueKeyType value) {
        this.valueKeyURI = value;
    }

    /**
     * Gets the value of the pairValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPairValue() {
        return pairValue;
    }

    /**
     * Sets the value of the pairValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPairValue(String value) {
        this.pairValue = value;
    }

}
